### ISSUE TITLE
Weird lighting issue

### ISSUE THREAD

**Issue by darrylryan** [Zylann/godot_heightmap_plugin#100]
I'm also getting a weird lighting issue where some quads seem to be lit differently to others (this screenshot is with my custom shader but same happens with both the classic4 shaders).

![image](https://user-images.githubusercontent.com/3797848/65389628-23d82200-dd50-11e9-8cdf-e4e5ea84234e.png)

**Comment by Calinou** [comment]
How many lights do you have in your scene? Do you have GIProbes or ReflectionProbes set up?

**Comment by darrylryan** [comment]
Just 1 directional light, no probes, and I've tried recreating the light and the environment to see if it was a bug there, but no change.

**Comment by darrylryan** [comment]
![image](https://user-images.githubusercontent.com/3797848/65392424-c6060300-dd6c-11e9-9c7e-cc5cfe1bd4ad.png)



![image](https://user-images.githubusercontent.com/3797848/65392416-a7077100-dd6c-11e9-837e-a39fc8b5ddab.png)

Looking at the wireframe it looks like maybe there's an issue with the drawing... there shouldn't be any colour in the wireframe view should there? Or has it baked it into the vertex colours?

**Comment by darrylryan** [comment]
![image](https://user-images.githubusercontent.com/3797848/65393040-a45c4a00-dd73-11e9-84d0-56d7a681b374.png)

Aha... I've found the issue... this is the normal image it has saved... for some reason it's only written it out for part of the terrain.

**Comment by Zylann** [comment]
Looks like normals didnt save properly. Which steps did you follow to get in that state?

**Comment by darrylryan** [comment]
I believe the reason may be that i imported a unity terrain and then edited just the area where i wanted to place a building.... so its written out a normal map for just the quads I touched.

**Comment by Zylann** [comment]
@darrylryan hmmm I would have expected the normal map to be generated when such import is done.

**Comment by Zylann** [comment]
I think it's caused by #101

**Comment by Zylann** [comment]
I fixed some related issues recently, maybe this one is solved now
