### ISSUE TITLE
Resizing a terrain causes the resized region to appear black

### ISSUE THREAD

**Issue by Zylann** [Zylann/godot_heightmap_plugin#102]
When a terrain is resized to become larger, the resized area will be black, even if not flat. This is not intented.
Perhaps there is a problem with `normalmap_baker.gd`.

**Comment by Zylann** [comment]
Part of the issue may be caused by https://github.com/godotengine/godot/issues/20614#issuecomment-534756903

**Comment by Woor** [comment]
I've encountered this too. It's the normal map that gets messed up on resize, the newly generated normals are wrong. As a workaround I manually open normal.png after the resize and color fill the proper color, before doing any terrain modifications.

**Comment by Zylann** [comment]
Should be fixed by f1136e89fcbdf22ce58a682c30ebb4b9b2bd4ad6
