### ISSUE TITLE
Grass patches disappearing when painting

### ISSUE THREAD

**Issue by Zylann** [Zylann/godot_heightmap_plugin#106]
Godot 3.2 alpha1

While updating the demo project, I noticed detail layers have a tendancy to disappear while painting, with an internal Godot error printed in the console (which I forgot to pick up). Something about `multimesh` count not matching or something like that.

When trying again I could not find a way to reproduce it yet, so I'm writing this issue to remember that there might be a bug here.

The terrain looks fine otherwise when playing the game, and the detail map is properly saved.

**Comment by Robbepop** [comment]
I experience this bug frequently but without an actual error appearing.
The solution is to paint another brush and save which makes all grass reappear, then you can simply undo the last brush placed.
It is a dirty solution but somehow works for now.
Hope this info was helpful.

**Comment by Zylann** [comment]
@Robbepop did you find a way to reproduce it reliably?

**Comment by Robbepop** [comment]
> @Robbepop did you find a way to reproduce it reliably?

Sadly, no.

**Comment by Zylann** [comment]
According to @Wallace99, this error can happen:

> servers/visual/visual_server_scene.cpp:726 - Condition "!is_geometry_instance(instance->base_type)" is true.

By the looks of it, this happens when calling `VisualServer.instance_set_custom_aabb`, and the error means that we are trying to use a RID which is not a `GeometryInstance`. `MultiMeshInstance` is one, so there are two possibilities:
- Either the plugin somehow messed up RIDs and sent something else, which I think is not the case because it uses a dedicated wrapper, which limits where RIDs are used: https://github.com/Zylann/godot_heightmap_plugin/blob/master/addons/zylann.hterrain/util/direct_multimesh_instance.gd
- The visual instance was not assigned a `MultiMesh` before calling `set_custom_aabb`, or the RID is pointing to a dangling instance. This one is more likely, however after looking at `https://github.com/Zylann/godot_heightmap_plugin/blob/master/addons/zylann.hterrain/hterrain_detail_layer.gd`, I can't see how that would happen.

**Comment by Zylann** [comment]
I pushed a fix in 2c2a73ecad6b963e31432b766f6a68c8d82c1e6f, let me know if it works
