### ISSUE TITLE
Map scale not updating due to wrong type hint

### ISSUE THREAD

**Issue by MilosLukic** [Zylann/godot_heightmap_plugin#107]
I had an issue with resizing map - it didn't work. I changed the type hint for the set_map_scale from float to Vector3 - it started working.

https://github.com/Zylann/godot_heightmap_plugin/blob/6dfdef3a558d1bb3e4f9a34822bfd4b7d60afc9e/addons/zylann.hterrain/hterrain.gd#L357

**Comment by Zylann** [comment]
Should be fixed in ff6ef20934f6dabc920979832affeafc515df01e
