### ISSUE TITLE
Invalid get index 'GROUND_ALBEDO_BUMP'

### ISSUE THREAD

**Issue by GammaGames** [Zylann/godot_heightmap_plugin#108]
After installing the addon in 3.2 I got the following errors:

```log
Updating detail layer material
Exit world
 scene/3d/navigation.cpp:144 - Condition ' !nm.linked ' is true.
Switch Scene Tab
Create HeightMap
HTerrainCollider: creating body
Set new data [Resource:41801]
Connecting new HeightMapData
HTerrainCollider: setting up heightmap
Create grid for lod 0, 32x32
Create grid for lod 1, 16x16
Create grid for lod 2, 8x8
Create grid for lod 3, 4x4
Create grid for lod 4, 2x2
Create grid for lod 5, 1x1
Set data done
Setting chunk size to 16
Chunk size snapped to 16
Enter world
Enter tree
Updating detail layer material
Transform changed
Updating detail layer material
Updating terrain material params
Edit [Spatial:98327]
 res://addons/zylann.hterrain/tools/texture_editor/texture_editor_dialog.gd:40 - Invalid get index 'GROUND_ALBEDO_BUMP' (on base: 'GDScript').
 res://addons/zylann.hterrain/tools/texture_editor/texture_editor.gd:35 - Invalid get index 'GROUND_ALBEDO_BUMP' (on base: 'GDScript').
Edit Null
 res://addons/zylann.hterrain/tools/texture_editor/texture_editor_dialog.gd:40 - Invalid get index 'GROUND_ALBEDO_BUMP' (on base: 'GDScript').
Edit [Spatial:98327]
 res://addons/zylann.hterrain/tools/texture_editor/texture_editor_dialog.gd:40 - Invalid get index 'GROUND_ALBEDO_BUMP' (on base: 'GDScript').
 res://addons/zylann.hterrain/tools/texture_editor/texture_editor.gd:35 - Invalid get index 'GROUND_ALBEDO_BUMP' (on base: 'GDScript').
 core/math/camera_matrix.cpp:294 - Condition ' !res ' is true. returned: false
```

My textures are empty:
![image](https://user-images.githubusercontent.com/7832163/66885373-56f98400-ef91-11e9-8bd7-3d7e85e82bb6.png)

I am unsure what went wrong, I didn't lose anything important but I thought I should still report it, in case it's affecting other users

**Comment by Zylann** [comment]
I have no idea what's going on here, `GROUND_ALBEDO_BUMP` is correctly defined in `HTerrain`.

**Comment by GammaGames** [comment]
I updated it through the in-engine addon installer, when I opened the scene again it looked like that. When I restart the editor it looks the same as it did, but I can remove the old terrain and it will work fine

**Comment by Zylann** [comment]
@GammaGames I think Godot did not properly reload the scripts. Also I think the idea of "updating" by just downloading over from the assetlib tab is a very bad idea... the plugin should be turned off, entirely removed first and then re-added because files can have been moved. Maybe that should be something to propose to Godot.

**Comment by GammaGames** [comment]
Do they have a proper way to update addons? I was updating to 3.2 and I can just load the project like normal, so I didn't expect to need any special procedure. I'll close this then, since it's likely not an issue with the plugin. Thank you!

**Comment by Zylann** [comment]
> Do they have a proper way to update addons?

Not really, that was my point :)
