### ISSUE TITLE
Render Distance locked at 500

### ISSUE THREAD

**Issue by UnmannedOcelot** [Zylann/godot_heightmap_plugin#110]
The "View Z-Far" setting seems to not be working. If I increase the setting from 500, it will take effect in the editor window. However, if I instance the terrain scene into another scene, the view distance is stuck at 500. Even in-game after increasing the camera's view distance.

Map editor window:
![2fb2cc038a1b428f186c5f9517c12d38](https://user-images.githubusercontent.com/53127422/68439830-aa28b600-018e-11ea-9e25-714e9fe7f268.png)

Main scene editor window:
![eefaace90fdb81cd4e6cddf47c92d808](https://user-images.githubusercontent.com/53127422/68439836-b4e34b00-018e-11ea-81fb-7a8586df75b0.png)

I would also like to add that when I originally created this map the other day, the view distance was working correctly. Now for some reason it is not working. Even if I create an entirely new map.

**Comment by Calinou** [comment]
IIRC, the editor camera settings are set on a per-scene basis, so you need to also set them in the main scene.

**Comment by UnmannedOcelot** [comment]
> 
> 
> IIRC, the editor camera settings are set on a per-scene basis, so you need to also set them in the main scene.
> 
> You can set default settings for the camera in the Editor Settings, but they won't apply to existing scenes (where local preferences will be used first).

Ah, I misunderstood how godot worked. Thank you for the reply.
