### ISSUE TITLE
Terrain Generation GUI scale

### ISSUE THREAD

**Issue by CuL8Rg8r** [Zylann/godot_heightmap_plugin#111]
Is there any way to make your plugin work on a large scale screen? I'm on a 4k and I cant use the terrain generator at all because the window doesn't scale with the sliders and buttons (they are all hidden behind the render preview window. Is there like a gui size setting I could change or something link an ini file for preference settings?

**Comment by Zylann** [comment]
Can you post a screenshot?

**Comment by ivantomac** [comment]
Editor settings:
![godot-editor-settings](https://user-images.githubusercontent.com/11358902/72216684-801db680-3578-11ea-9ea6-861ddd460442.png)

Generate terrain dialog:
![godot-generate-terrain-1](https://user-images.githubusercontent.com/11358902/72216688-90359600-3578-11ea-80fc-37f54e8ee5fb.png)

Generate terrain dialog after resizing it:
![godot-generate-terrain-2](https://user-images.githubusercontent.com/11358902/72216692-9f1c4880-3578-11ea-8663-4450132de0bf.png)

Some other things are also a bit off but this one is the most notable one.

**Comment by Calinou** [comment]
Unfortunately, there's no way to get the current editor scale from GDScript, so you'll have to add a setting or try to infer it from the resolution and screen DPI [like the engine does](https://github.com/godotengine/godot/blob/5fede4a81c67961c6fb2309b9b0ceb753d143566/editor/editor_node.cpp#L5515-L5554). Otherwise, the GUI will have to be modified to ensure nothing can overlap.

**Comment by Zylann** [comment]
Actually looking at the UI, it mostly seems `minimum_size` is not being affected by the DPI resizing.
In the second screenshot of https://github.com/Zylann/godot_heightmap_plugin/issues/111#issuecomment-573396567, it's actually two parts of an HBoxContainer overlapping with each other. How is that even possible? Such container usually doesn't permit that Oo

**Comment by Zylann** [comment]
Ok, with a bunch of digging, I managed to fix the UI in 1.5x DPI, so I hope it would work for 2x as well.
Improvement made in b4ac92ca799dc6c96f5514c06f13b0f63031defe
