### ISSUE TITLE
Inspector properties disappear after selecting custom shader type

### ISSUE THREAD

**Issue by ardawan** [Zylann/godot_heightmap_plugin#114]
add height terrain to my node and try to play with the options. after selecting the shader type to custom,  the rest of the properties gone.

before
![Screenshot 2019-11-26 at 3 09 48 PM](https://user-images.githubusercontent.com/6112301/69606996-3b3ccf80-105f-11ea-8952-471241ad2809.png)

after
![Screenshot 2019-11-26 at 3 09 56 PM](https://user-images.githubusercontent.com/6112301/69607011-455ece00-105f-11ea-97e0-362e08991b33.png)

**Comment by Zylann** [comment]
Any error printed in the console as you do this?

**Comment by Zylann** [comment]
Should be fixed with 5c3e519cf10844988d03cb2fe4f0734b48d2b02e
