### ISSUE TITLE
Broken in 3.2, "Assertion Failed"

### ISSUE THREAD

**Issue by nathanwfranke** [Zylann/godot_heightmap_plugin#115]
Console always spams "Assertion failed"
For example,
```
SCRIPT ERROR: run: Assertion failed.
   At: res://addons/zylann.hterrain/tools/generator/texture_generator.gd:140.
```
When I try to generate terrain

**Comment by Zylann** [comment]
I cannot reproduce this. Can you provide more specific reproduction steps?

**Comment by nathanwfranke** [comment]
Brand new project, add the terrain plugin
New Scene with Spatial, add HTerrain child. In the top context menu click on Terrain->Generate and it will show the bug
OS: Ubuntu 19.10 eoan
Kernel: x86_64 Linux 5.3.0-23-generic
And I'm using GLES3

**Comment by Zylann** [comment]
The generator currently doesn't work if you haven't specified a data folder for the terrain. In other words, the terrain has no data resource assigned internally, so the generator doesn't know on which data it has to work on.
