### ISSUE TITLE
Collider doesn't work and/or documentation missing

### ISSUE THREAD

**Issue by codecat** [Zylann/godot_heightmap_plugin#116]
I've been trying to set up a terrain for physics, but have been unable to make it work. The documentation doesn't mention collisions much, so I'm not sure if I'm doing something wrong.

I looked through code and also a number of similar issues here on github, but can't figure it out. I believe I do need the project to be using Bullet physics, which I selected but still nothing seems to work.

The console does show `HTerrainCollider: setting up heightmap` when starting the scene so I'm assuming everything is set up correctly.

(Godot 3.1.2, and the latest master branch commit on Git here)

**Comment by Zylann** [comment]
There seems to be a problem in 3.1.2 for the master version of the plugin, do you see errors in the console?

**Comment by codecat** [comment]
Awesome! Seems to work on my end now when updating from master. Thanks!
