### ISSUE TITLE
Slight imprecision in imported heightmap

### ISSUE THREAD

**Issue by paxetgloria** [Zylann/godot_heightmap_plugin#118]
Hi @Zylann, first of all thank you for your work on this plugin, I honestly appreciate your effort!

I'm re-writing my Blender addon called bLandscapeTools(bLT) to B2.8 and decided to use Godot and your plugin to showcase some of bLT features. 

I exported raw heightmap(513x513) with unsigned integer values ranging from 0 to 65535. Height values of the terrain mesh in Blender are ranging from 0 to 28 meters above sea level. If I import raw having ranges set properly(min=0,max=28), there where terrain is at its max(28m) I get something like 27.984m after import. I looked into zylann.hterrain/hterrain_data.gd -> func _import_heightmap
and the fact you're dividing value read from raw file by 65536 seems to be causing this imprecision.
`var gs = float(f.get_16()) / 65536.0`
It should be 65535.0, then it works correctly for me.

Best regards,
Miro Horvath

**Comment by Zylann** [comment]
Note that the heightmap is stored using half-precision floats so there will always be a tiny bit if imprecision (the taller it is, the bigger the difference can be).

**Comment by Zylann** [comment]
Fixed in 0c8848c3fdeb940d67d5852f48186370e40c3532
