### ISSUE TITLE
Can't find any HTerrain node.

### ISSUE THREAD

**Issue by CyberFoxHax** [Zylann/godot_heightmap_plugin#119]
Downloaded from Godot AssetLib. Also tried from Git.

Read the manual.

> **Creating a HTerrain node**
Features of this plugin are mainly available from the HTerrain node. To create one, click the + icon at the top of the scene tree dock, and navigate to this node type to select it.

These is no such node.

**Comment by Zylann** [comment]
- Which version of Godot are you using?
- Did you enable the plugin in your project settings?
- Did you see any error in the system console?

**Comment by CyberFoxHax** [comment]
Your second point caught my attention. And sure enough it was marked as "Inactive". The HTerrain node now exists as intended.

I recommend amending the documentation.

By the way, this is incredible, how long did it take you write this monster?
