### ISSUE TITLE
Custom shader behavior strangely : VERTEX position is not uniform across the map

### ISSUE THREAD

**Issue by omomthings** [Zylann/godot_heightmap_plugin#124]
I It looks like the VERTEX position in the custom shader is behaving strangely. I created a simple custom shader that draws a grid. But on a height map the lines are not straight even at close view. Tested on a plane meshinstance with same dimensions works fine.

Variable definition is simple
`//This holds the vertex position
varying vec2 vertex_position

// Width of the line to draw
uniform float grid_line_width = 1.0`

Code added in vertex function
`
if(show_grid){
vertex_position = VERTEX.xz;
}`

Code added at the bottom of the fragment function
`
if (show_grid){

//Draw a column each 10 units
if (mod(vertex_position.x, 10.0) < grid_line_width){
ALBEDO = vec3(1.0,0.0,0.0);
}

// Draw a row each 10 units
if (mod(vertex_position.y, 10.0) < grid_width){
ALBEDO = vec3(1.0,0.0,0.0);
}
`

Here is the result obtained on a 512x512 flat unmodified height map:
![image](https://user-images.githubusercontent.com/13408887/74717823-591a6a80-5231-11ea-8e50-7c908958945a.png)

I'm I missing something here as it's actually simple. Feels like the VERTEX position is not uniform across the map.

**Comment by Zylann** [comment]
The result is pretty much watertight, I'm intrigued that you get offsets like this. Did you check wireframe mode? Note that LOD produces meshes of varying sizes and varying border geometries.

**Comment by omomthings** [comment]
Even at close view the artifacts were still there, so the LOD is not to blame.
But your second proposition helped me fix my problem actually. You were right, the `VERTEX` points to the mesh local coordinates, I used the absolute coordinates and it worked perfectly fine. 
Thanks a lot, and thanks for all the great job you did with the tools!
