### ISSUE TITLE
Using Half-Resolution under Viewport settings offsets the reticule.

### ISSUE THREAD

**Issue by Wasabi-Cheetah** [Zylann/godot_heightmap_plugin#132]
The problem is that when I use the focus shortcuts F or O, the reticule is then offset. 

Update: it's actually using the half-resolution setting under the viewport settings that causes that bug.
![Godot Terrain Offset](https://user-images.githubusercontent.com/45925149/77711087-30526700-6f8d-11ea-8d25-c0761bc6a51a.gif)

**Comment by Zylann** [comment]
This is the code I use to project the mouse position:
https://github.com/Zylann/godot_heightmap_plugin/blob/a27c289fa77ca2deac2f511798e4caf12f269147/addons/zylann.hterrain/tools/plugin.gd#L369

It needs to take into account the editor viewport size compared to the size of its container. Usually the ratio is 1:1 but I think in the case of half-resolution the ratio will be different.

**Comment by Zylann** [comment]
Turns out I actually have no idea how to do this. The API doesn't seem to expose what I need.
If I use `get_viewport()` on the terrain node, I get a viewport but it has size `(0, 0)`. Its parent is a `Control` node of size `(0, 0)` as well, completely useless.

**Comment by Zylann** [comment]
Fixed in 74e40a4e592d6819510af5cb49668e8b5798484b

**Comment by Wasabi-Cheetah** [comment]
Awesome!!!
