### ISSUE TITLE
Terrain not showing outside the editor

### ISSUE THREAD

**Issue by ObiDriftKenobi** [Zylann/godot_heightmap_plugin#134]
I'm pretty sure this is my fault, and not the plugin's fault, but I was searching the internet for a fix for 30 minutes now and I'm clueless.

I installed the plugin, generated a terrain, painted it with my textures and was ready to play test it. The terrain was not showing though. The camera preview looks like this:
![image](https://user-images.githubusercontent.com/35656715/77819829-2be99380-70de-11ea-9c7f-a76861337ce9.png)
And this is what is shown in game.
![image](https://user-images.githubusercontent.com/35656715/77819842-43c11780-70de-11ea-9ee1-836300157883.png)

If this is my fault, how do I fix this?
Godot version: 3.1.1

**Comment by Zylann** [comment]
Does it happen too in Godot 3.2.1?
Which renderer, graphics card and OS do you have? Anything printed in the console?
Do you have a test project?

**Comment by ObiDriftKenobi** [comment]
This problem fixed itself.

I saved the project then reopened it later, my terrain was gone. I generated a new one, and then it worked.

Weird flex but ok.
