### ISSUE TITLE
Unable to export heightmap to 8 bit png

### ISSUE THREAD

**Issue by Wallace99** [Zylann/godot_heightmap_plugin#139]
**Describe the bug**
I wanted to be able to export the heightmap as a png (not too bothered about losing precision as I'm working on trying to generate areas to put trees and plants by combining the heightmap with other noise images), but when I export it just creates a solid red png and gives the following output in the console: 

>  Can't open dynamic library: /Applications/Godot.app/Contents/MacOS/../Frameworks/hterrain_native.dylib, error: dlopen(/Applications/Godot.app/Contents/MacOS/../Frameworks/hterrain_native.dylib, 2): image not found.
 modules/gdnative/gdnative.cpp:483 - No valid library handle, can't get symbol from GDNative object
 modules/gdnative/nativescript/nativescript.cpp:1506 - No nativescript_init in "res://addons/zylann.hterrain/native/bin/osx/hterrain_native.dylib" found
 Image must be locked with 'lock()' before using get_pixel().
 Image must be locked with 'lock()' before using get_pixel().
 Image must be locked with 'lock()' before using get_pixel().
 Image must be locked with 'lock()' before using get_pixel().
 Image must be locked with 'lock()' before using get_pixel().
 Image must be locked with 'lock()' before using get_pixel().
 Image must be locked with 'lock()' before using get_pixel().
 Image must be locked with 'lock()' before using get_pixel().
 Image must be locked with 'lock()' before using get_pixel().
 Image must be locked with 'lock()' before using get_pixel().
 Image must be locked with 'lock()' before using get_pixel().
 Image must be locked with 'lock()' before using get_pixel().
 Image must be locked with 'lock()' before using get_pixel().
 Image must be locked with 'lock()' before using get_pixel().

**To Reproduce**
1. Click terrain
2. Click export heightmap
3. Click auto height range, fill in output field, select 8 bit png
4. Click export
5. Exported heightmap is solid red and console logs errors

**Expected behavior**
Expected to see heightmap in exported image

**Screenshots**
[https://i.ibb.co/VYSXw5n/Screen-Shot-2020-04-05-at-9-39-24-AM.png](url)

**Environment**
- OS: MacOS Catalina
- Graphics card AMD Radeon Pro 560X 
- Godot version 3.2.stable.official
- Plugin version (commit) 4dd9d0cbc7d178289ebb5a13666ae0b4b056ae94
- Renderer used: OpenGL ES 3.0

**Comment by Zylann** [comment]
> Can't open dynamic library: /Applications/Godot.app/Contents/MacOS/../Frameworks/hterrain_native.dylib, error: dlopen(/Applications/Godot.app/Contents/MacOS/../Frameworks/hterrain_native.dylib, 2): image not found.

I am very curious how you are getting this. I never compiled an OSX version of that library yet, and it's not even in the list of supported OSes in `factory.gd` Oo
It looks unrelated to exporting to 8 bit PNG, though.

> Screenshots
https://i.ibb.co/VYSXw5n/Screen-Shot-2020-04-05-at-9-39-24-AM.png

Link doesn't work

**Comment by Zylann** [comment]
The console errors should be fixed by 5ca0f9aa6d7f3ed0923453bba02ecae6236a492a
The 8-bit PNG exort should be fixed by b7d928153b97a06910e06ee8e600a60894c19364
