### ISSUE TITLE
Can't remove detail paint

### ISSUE THREAD

**Issue by phelioz** [Zylann/godot_heightmap_plugin#143]
**Describe the bug**
When trying to lower the detail density to paint over a already painted area it will only override if the density value is larger than the already painted value. Which in turn makes it impossible to remove detail paint

**To Reproduce**
1. Create new project
2. Create scene and add HTerrain
3. Setup up terrain folder
4. Add detail layer
5. Paint detail
6. Try to remove by reducing detail intensity <- Which doesn't work

**Expected behavior**
When you paint with lower density value it should override the already painted density value.

**Environment**
- OS: Windows
- Graphics card 970 GTX
- Godot version 3.2.1
- Plugin version 1.2
- Renderer used: GLES3

**Comment by Zylann** [comment]
Turns out it's a side effect of using the L8 image format. The brush only modifies the R channel since it's supposed to be a monochrome image, however in Godot, `set_pixel` does this:

**Comment by phelioz** [comment]
I see, appreciate the fast response. 

Inside the function:
`void ImageUtils::lerp_channel_brush(Ref<Image> image_ref, Ref<Image> brush_ref, Vector2 p_pos, float factor, float target_value, int channel) const {
    ERR_FAIL_COND(image_ref.is_null());
    ERR_FAIL_COND(brush_ref.is_null());
    Image &image = **image_ref;
    Image &brush = **brush_ref;

    generic_brush_op(image, brush, p_pos, factor, [target_value, channel](Image &image, int x, int y, float b) {
        Color c = image.get_pixel(x, y);
        c[channel] = Math::lerp(c[channel], target_value, b);
        image.set_pixel(x, y, c);
    });
}`

Could we not just set the g and b channels too before we do the image.set_pixel(x, y, c)?
Because right now in the code you don't use lerp_channel any other way that would conflict with this I think.
Or we could create a new lerp_channel like function that just does this.

**Comment by Zylann** [comment]
Should be fixed in c4c1da5fdfe50c856d0dbbfbfa685c25656aeb83

**Comment by phelioz** [comment]
That's great! thanks :)
