### ISSUE TITLE
Strange squares that can't have detail layer drawn over them

### ISSUE THREAD

**Issue by Wallace99** [Zylann/godot_heightmap_plugin#146]
<img width="970" alt="Screen Shot 2020-04-12 at 9 53 38 PM" src="https://user-images.githubusercontent.com/5481339/79066127-7176a500-7d09-11ea-92ad-b35d3b8941a3.png">

**Describe the bug**
While using the grass paint tool to place grass over my terrain there seem to be a handful of squares in the terrain that it won't allow me to paint over. I've noticed this error in the console when moving around the terrain in the editor:  

> servers/visual/visual_server_scene.cpp:726 - Condition "!is_geometry_instance(instance->base_type)" is true.

**To Reproduce**
Not too sure if this is specific to my terrain or not?
1. Generate 1025x1025 terrain, paint with texture etc
2. Add detail layer with texture
3. Paint over majority of terrain
4. See perfect square patches that have no detail and do not show detail when brush used over them
Linking a reproduction project may help.
If you see any errors in the console, that may also help.

**Expected behavior**
Any part of the terrain to be able to be painted with grass

**Screenshots**
Attached above. Square is to the left of the cursor

**Environment**
- OS: MacOS Catalina
- Graphics card: AMD Radon Pro 560X
- Godot version: v3.2.stable.official
- Plugin version: a4d0a55493994bcf10b668ff1272ca1655c2ab32
- Renderer used: GLES3

**Comment by Zylann** [comment]
That looks related to https://github.com/Zylann/godot_heightmap_plugin/issues/106

**Comment by Wallace99** [comment]
Ah looks to be gone when restarting the editor. I do however get this error in the output when I try to paint using the latest commit though:

>  res://addons/zylann.hterrain/hterrain_brush.gd:383 - Invalid call to function 'lerp_color_brush' in base 'Reference (image_utils_generic.gd)'. Expected 5 arguments.

**Comment by Zylann** [comment]
That error log you just got should be fixed in e3af97514b823dfcb4210a383955b7d7c76dc0aa
