### ISSUE TITLE
Support smaller sized terrains

### ISSUE THREAD

**Issue by sampengilly** [Zylann/godot_heightmap_plugin#148]
**Is your feature request related to a problem? Please describe.**
I would like to add terrain to my environment in smaller chunks that are easier to manage (e.g. small, contained outdoor scenes). It would be beneficial to simply add a small terrain node for each contained environment rather than creating a large one which will go mostly unused.

**Describe the solution you'd like**
The resize terrain window should support smaller or custom sizes (or this option should be more readily available in the inspector / when creating terrain data). A maximum size limit is fine, as is keeping the sizes square.

**Describe alternatives you've considered**
I tried making local modifications to the library to achieve this but ended up with strange results. Other considerations involve custom meshes which will either need new tools which start to approach into the domain of this plugin, or horrible workflows between Godot and 3d modelling tools.

**Additional context**
Nil

**Comment by Zylann** [comment]
In theory, lower terrain resolutions can be 257x257, 129x129 and 65x65, the latter being one single chunk, considering maximum chunk size. But at such a tiny size, level of detail becomes useless, and a normal mesh would just work better (even Unity doesn't provide such small sizes).
It doesn't cost anything to allow it, though.
Which size do you need?

> horrible workflows between Godot and 3d modelling tools

That's a shame^^" considering that workflow is supposed to be the main way to work in 3D

> I tried making local modifications to the library to achieve this but ended up with strange results. 

What did you try?

**Comment by sampengilly** [comment]
> That's a shame^^" considering such workflow is supposed to be the main way to work in 3D

I mean mostly in the back and forth editing aspect, levels tend to need to be more fluid than props and characters, and need more tweaking. Which is easier to do with in-editor tools.

> What did you try?

I tried modifying the set of sizes where I could see them (in the resize window), it was a while ago now so I can't quite remember where else I looked and what the exact results were, but the "simple" change didn't seem to work for me (probably overlooked something since I don't know the system well enough). I could probably give it another go

> But at such a tiny size, level of detail becomes useless, and a normal mesh would just work better.

I did consider that, but for a single chunk, even if LOD isn't needed, there's the savings on not drawing or processing any other chunks that aren't needed.

Another thought, would it make more sense for the tools to have "Chunk Size" and "Number of Chunks to a side" as the properties rather than the current setup of chunk size and then the disconnected size values in the resize window?

**Comment by Zylann** [comment]
> Another thought, would it make more sense for the tools to have "Chunk Size" and "Number of Chunks to a side" as the properties rather than the current setup of chunk size and then the disconnected size values in the resize window?

Chunk size and terrain size are actually closely related. One is multiple of the other by a power of two, which is what allows LOD to work. Chunk size is a bit configurable too, it can be set to 16, 32 or 64, which is why 64 is the minimum resolution a terrain can have. If you need 32, maximum chunk size may need to dynamically reduce, which adds to the complexity so I'm not sure if it's worth going that low.

**Comment by Zylann** [comment]
Smaller sizes should be available in f614de19c222977694da4bdec0b13a356335cf25
