### ISSUE TITLE
Low-poly style?

### ISSUE THREAD

**Issue by wacyym** [Zylann/godot_heightmap_plugin#150]
Hello!
How can i turn off smooth terrain shading to flat shading?
Example picture:
![image](https://user-images.githubusercontent.com/6958185/79562294-dccec700-80bb-11ea-89dd-ecb42bd231e5.png)

If i understand correctly i need to change something in simple4.shader file?
Can you please help - what exactly i need to change?

**Comment by Zylann** [comment]
I'm not exactly sure what changes are needed but my first thought would be to turn off interpolation of normals (which is normally a `varying`) using the `flat` keyword. Another way would be to make chunk meshes have non-shared vertices. In both cases it may also require to copy/paste (again) the whole shader to handle this properly.

**Comment by wacyym** [comment]
Yes, looks like flat keyword helps in "varying flat vec4 v_tint;"
But shadows still has soft shading:
![image](https://user-images.githubusercontent.com/6958185/79641851-031f6000-81ab-11ea-99a2-1162585313ad.png)

I think it would be a nice feature: to be able to turn off any filtering/smoothing/interpolation

**Comment by Zylann** [comment]
These are not shadows, these are the normals. They might not have a dedicated `varying` though, so in your screenshot they are still interpolated. You may need to change the shader to make them flat somehow, getting it from the vertex shader instead of fragment, maybe.

**Comment by Calinou** [comment]
Can we use a shader to "flatten" smooth normals using derivatives or something like that? Vertices would still be smooth (and edges wouldn't be splitted), but it would *look* flat.

**Comment by wacyym** [comment]
Hi @Zylann, thanks for explanation, i was trying to modify shader - but all my attempts failed.. Im in bad relationship with shaders :)
Can you please help with it enhancement? if this not difficult for you, or you have free time

**Comment by matthew798** [comment]
@wacyym  does this solve your problem? [](https://github.com/Dimev/Godot-Low-Poly)

**Comment by matthew798** [comment]
I am wondering if it is possible to reduce the subdivison of the PlaneMesh. I am using the shader I linked above, but the terrain has so many triangles that it still doesn't look quite like I want. Is there a way to reduce the amount of triangles on the plane?

**Comment by Zylann** [comment]
After tinkering a bit by taking the `classic4_lite` as base, I removed a bunch of stuff and came up with a shader that makes normals and color low-poly:

```glsl
shader_type spatial;

uniform sampler2D u_terrain_heightmap;
uniform sampler2D u_terrain_normalmap;
uniform sampler2D u_terrain_colormap : hint_albedo;
uniform mat4 u_terrain_inverse_transform;
uniform mat3 u_terrain_normal_basis;

varying flat vec4 v_tint;

vec3 unpack_normal(vec4 rgba) {
	return rgba.xzy * 2.0 - vec3(1.0);
}

void vertex() {
	vec2 cell_coords = (u_terrain_inverse_transform * WORLD_MATRIX * vec4(VERTEX, 1)).xz;

	// Normalized UV
	UV = cell_coords / vec2(textureSize(u_terrain_heightmap, 0));
	
	// Height displacement
	float h = texture(u_terrain_heightmap, UV).r;
	VERTEX.y = h;
	
	v_tint = texture(u_terrain_colormap, UV);
	
	// Need to use u_terrain_normal_basis to handle scaling.
	// For some reason I also had to invert Z when sampling terrain normals... not sure why
	NORMAL = u_terrain_normal_basis * (unpack_normal(texture(u_terrain_normalmap, UV)) * vec3(1,1,-1));
}

void fragment() {
	if (v_tint.a < 0.5) {
		discard;
	}
	
	vec3 terrain_normal_world = u_terrain_normal_basis * (unpack_normal(texture(u_terrain_normalmap, UV)) * vec3(1,1,-1));
	terrain_normal_world = normalize(terrain_normal_world);
	
	ALBEDO = v_tint.rgb;
	ROUGHNESS = 1.0;
	NORMAL = normalize(cross(dFdx(VERTEX), dFdy(VERTEX)));
}
```

It doesn't have ground textures but it's not always necessary for this kind of art style.

**Comment by wacyym** [comment]
Thanks a lot @Zylann! exactly what needed.
I think some users may find it useful, so maybe you will add this shader as optional?

**Comment by Zylann** [comment]
I could add it in a future update yes, at least as a starting point for people to customize because I can imagine it calls for tweaks.

**Comment by Zylann** [comment]
9c31aa68cd4c1674e1e600461e6712df9005d6a2 adds the low poly shader from my previous post as a built-in preset.
