### ISSUE TITLE
What is the license of this Project?

### ISSUE THREAD

**Issue by LeonWilzer** [Zylann/godot_heightmap_plugin#152]
This repository doesn't seem to have a license associated with it. It would be great if it included a permissive one like the MIT License.

**Comment by Calinou** [comment]
The license file is in the [addon directory](https://github.com/Zylann/godot_heightmap_plugin/blob/master/addons/zylann.hterrain/LICENSE.md). This was probably done so the license isn't detached from the add-on when you paste it into a project.

I suppose it could be copy-pasted at the repository root so GitHub can detect it.

**Comment by LeonWilzer** [comment]
> This was probably done so the license isn't detached from the add-on when you paste it into a project.

I see

> I suppose it could be copy-pasted at the repository root so GitHub can detect it.

Yeah, that might help people discover the project more easily, although it shouldn't really matter.

Also, I am sorry I bothered you.

**Comment by Calinou** [comment]
> Also, I am sorry I bothered you.

No problem at all :slightly_smiling_face:
