### ISSUE TITLE
Exported game crashes on launch

### ISSUE THREAD

**Issue by Duroxxigar** [Zylann/godot_heightmap_plugin#153]
**Describe the bug**
When using the plugin on Godot 3.2.1, on export, the game crashes while trying to load.

**SCRIPT ERROR: GDScript::load_byte_code: Parse Error: The identifier "EditorSettings" isn't a valid type (not a script or class), or couldn't be found on base "self".**

This is on line 219 of the **util.gd** script. It is complaining about the parameter. I removed the type-hint and exported the game again. The game no longer crashed.

I don't know if this is something specific to the tool or a problem with Godot itself however, as **EditorSettings** should be a class that you can use as a type-hint.

**To Reproduce**
Create a project with this plugin and export the game.

**Expected behavior**
The game to not crash on load

**Screenshots**
![image](https://user-images.githubusercontent.com/16636969/79624616-cc850f00-80f0-11ea-9065-1d64d5a4ca41.png)

**Environment**
- OS: Windows 10
- GTX 1060 6GB
- Godot 3.2.1
- Plugin Version: 1.2
- Renderer used: GLES3

**Comment by Zylann** [comment]
Two things:
- Editor-specific stuff in `util.gd` must be separated in another file under the `tools/` folder
- The `tools/` folder must be added to the list of ignored folders on export in your project settings, if that's still a thing

**Comment by Zylann** [comment]
The function with the offending class should no longer be loaded in 27dd2de2023d03cf922eddcb4f02ddaf76bf6cb9

Can you check if that fixes the error for you?
