### ISSUE TITLE
KinematicBody moved with move_and_slide falls through terrain that is not flat

### ISSUE THREAD

**Issue by matthew798** [Zylann/godot_heightmap_plugin#154]
**Describe the bug**
Using a `KinematicBody`, moved with `AnimationTree.get_root_motion_transform.origin` fed to `move_and_slide` causes the `KinematicBody` to fall through the terrain wherever the angle changes.

That is to say, at the junction where the terrain goes from flat to angled, the kinematic body will fall through the terrain. Flat terrain works as expected.

**To Reproduce**
[Open and run this project](https://drive.google.com/open?id=1R8G-nmWTOIG55_3GapiIW96tTpHi45iG)

In this demo, the character will start walking forward right away, and will quickly fall through the terrain as there is a *very* slight incline right in front of the character.

**Expected behavior**
The character collides and slides with the terrain collider, remaining above the terrain

**Environment**
- OS: Manjaro Linux
- Graphics card: Intel UHD 620
- Godot version: 3.2.stable
- Plugin version: 1.2
- Renderer used: GLES3

**Comment by Zylann** [comment]
As fas as I know, the terrain uses a HeightMap collision shape, which is implemented in Bullet inside Godot. There is nothing special the plugin does with it, so I can't really help you. Raycasts work and dropping cube rigidbodies also work. Maybe there is a problem in your code or Godot's Kinematic Body?

**Comment by matthew798** [comment]
Hmm, strange...

Ill have to post this on reddit or so.

BTW, just wanted to say a heartfelt thanks for all the work you've put into this tool. This should become the built in standard way of doing terrain in Godot. Absolutely fantastic.
