### ISSUE TITLE
Lower tool does nothing

### ISSUE THREAD

**Issue by tinmanjuggernaut** [Zylann/godot_heightmap_plugin#157]
**Describe the bug**
Lower tool draws the circle but has no effect. The other tools work fine.

**To Reproduce**
Make a new terrain.
Use the lower tool.

**Environment**
Win10/64
GTX 1060/6gb
Godot 3.2.1
fb997981d5b40d1f572c2c89f1b3c0ef7fd0f1c0

First time using this plugin and it's pretty great. We started using it on a game jam 9 days ago (done now) with v1.2. That version works fine except lower tool does nothing on two different computers. Mine above and a win8.1/GT430.

I just upgraded to master and created a new project file. The lower button still does nothing.

Using the master hash above, I created a new game project, new scene, new terrain dir, raised a few bumps, tried to lower and got nothing. The console reports this:
```
Godot Engine v3.2.1.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 1060/PCIe/SSE2

erasing C:\Users\cory\AppData\Roaming/Godot/projects/New Game Project-a9fa6dc079ae044029f72a418a458d9c/filesystem_update4
SCRIPT ERROR: GDScript::reload: Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
          At: res://addons/zylann.hterrain/hterrain_data.gd:7
ERROR: reload: Method failed. Returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:576
SCRIPT ERROR: GDScript::reload: Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
          At: res://addons/zylann.hterrain/hterrain_resource_loader.gd:6
ERROR: reload: Method failed. Returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:576
ERROR: Script does not inherit a CustomResourceLoader: res://addons/zylann.hterrain/hterrain_resource_loader.gd.
   At: core/io/resource_loader.cpp:949
WARNING: load: Loaded resource as image file, this will not work on export: 'res://terrain1/normal.png'. Instead, import the image file as an Image resource and load it normally as a resource.
     At: core/image.cpp:1884
```

I get this when I use either the raise or lower terrain:
```
SCRIPT ERROR: request_tiles_in_region: Assertion failed.
          At: res://addons/zylann.hterrain/tools/normalmap_baker.gd:77
```

**Comment by Zylann** [comment]
Yes, the lower tool doesn't work with GDNative enabled. I noticed but forgot to note it down...
There is a clamp preventing negative factors which should probably removed: https://github.com/Zylann/godot_heightmap_plugin/blob/fb997981d5b40d1f572c2c89f1b3c0ef7fd0f1c0/addons/zylann.hterrain/native/src/image_utils.cpp#L14

The errors you posted are something else entirely, but not sure what.

**Comment by Zylann** [comment]
Lower brush should be fixed with 27a61517f91ec6445eebc9469da0e611a51e38a4

**Comment by tinmanjuggernaut** [comment]
Excellent, thank you. Works great.

BTW, I also have a lot of these errors:
```
ERROR: call: hterrain_detail_layer.gd: Terrain data is null, can't update detail layer completely
   At: modules/gdscript/gdscript_functions.cpp:803
ERROR: get_tree: Condition "!data.tree" is true. Returned: __null
   At: scene/main/node.h:281
```

**Comment by tinmanjuggernaut** [comment]
Depth blend is awesome. Wish we could have all of these texturing, sculpting, and generation tools in voxel tools. :)
