### ISSUE TITLE
Can't set PNG as detail layer image

### ISSUE THREAD

**Issue by matthew798** [Zylann/godot_heightmap_plugin#158]
**Describe the bug**
When attempting to set the image of an HTerrainDetailLayer, the following error message appears:

> The selected resource (StreamTexture) does not match any type expected for this property (Image).

The file is a PNG image.

Interestingly, I can use the "height.res" file as a detail, but no PNG images work.

**To Reproduce**
1. Create a terrain in a new project
2. Create a detail layer
3. Attempt to select a PNG image by browsing
NOTE** Drag-and-drop will not produce the error, the image simply won't be added.

**Expected behavior**
The image will be added correctly

**Environment**
- OS: Linux Manjaro
- Graphics card: intel UHD 620
- Godot version: 3.2.stable
- Plugin version (or commit hash if you got it from Github directly)
- Renderer used: note that GLES2 is not supported.
![grass_1](https://user-images.githubusercontent.com/379965/80103975-e0db6880-8543-11ea-85e8-8e37cb08d648.png)
![error](https://user-images.githubusercontent.com/379965/80103983-e638b300-8543-11ea-96e0-546b9279a301.png)

**Comment by Zylann** [comment]
Works fine when I test it:
![image](https://user-images.githubusercontent.com/1311555/80129324-cbd7f700-858e-11ea-8e0e-fc5d5b70dc2f.png)

> The selected resource (StreamTexture) does not match any type expected for this property (Image).

The property definitely isn't expecting an `Image`: https://github.com/Zylann/godot_heightmap_plugin/blob/7368f5df6e0c45f9ccb8976d904e3875005b5f1c/addons/zylann.hterrain/hterrain_detail_layer.gd#L39

I don't know what's going on here.

**Comment by matthew798** [comment]
Ahh I figured it out. I was adding a new image texture, setting the grass as the image then trying to use that as the terrain "texture". Turns out I just needed to use the image directly.
