### ISSUE TITLE
Plugin Doesn't Activate on Ubuntu

### ISSUE THREAD

**Issue by seesemichaelj** [Zylann/godot_heightmap_plugin#160]
**Describe the bug**
The `HTerrain` node isn't available for selection, so I'm assuming the plugin hasn't successfully been activated.

**To Reproduce**
1. Install via the `AsssetLib` tab within Godot
1. Reload the project where there isn't a main scene yet
1. Click the plus sign to add a node
1. Type `HTerrain` in the search, and note there isn't a node available

**Console Output**

The only output I see in the terminal as well as the `Output` panel is the `does not have a library for the current platform.` error that is observed in #156

**Expected behavior**
To be able to add the HTerrain node

**Screenshots**

![image](https://user-images.githubusercontent.com/549323/80579098-53be6680-89be-11ea-9ba9-31009658f308.png)

**Environment**
- OS: Ubuntu 20.04
- Graphics card: NVIDIA GTX 970/PCIe/SSE2
- Godot version 3.2.1
- Plugin version 1.2.1
- Renderer used: GLES3

**Comment by seesemichaelj** [comment]
Well this was my first plugin I've used in Godot. The issue is that the plugin doesn't come activated by default. You need to go to Project > Project Settings > Plugins > and click the drop down to activate it

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot-proposals/issues/324.
