### ISSUE TITLE
Allow to import EXR heightmaps

### ISSUE THREAD

**Issue by Muzz** [Zylann/godot_heightmap_plugin#163]
**Is your feature request related to a problem? Please describe.**
Very few bits of professional software support raw to export(or at least, affinity photo and houdini both don't), and png is not suitable for the task at hand. 16 bit Exr works great. 

**Describe the solution you'd like**
I personally hacked in very simple support for this. But reading the older posts it seems to be something you want to support but aren't doing for performance reasons. 

So I would like to just have an issue i can actually track, and talk about the issue with. 

**Describe alternatives you've considered**
It was easier hacking this in than considering alternatives, but would nice to have it in the actual repo.

**Comment by Muzz** [comment]
[height.zip](https://github.com/Zylann/godot_heightmap_plugin/files/4603279/height.zip)
Heres a test file for you as well. It's got the height data in the red channel, generated from houdini.

**Comment by Muzz** [comment]
Ah I did some more searching. Seems that You want this to happen, but right now it's inefficient to do this? I'll keep working with is as it's impractical with my tool chain to use raw, and consider using the raw for actual builds.

**Comment by Zylann** [comment]
EXR is supported for *import* and *export*. What I meant in posts where "EXR is not supported" is about the internal format used by the plugin. If you want to obtain the heightmap as EXR or import an existing one, this is currently supported.

**Comment by Muzz** [comment]
Hmm, The import menu didn't have exr on it, only png and raw. So I'm a bit confused by this?

Perhaps i'm using an old version without realizing?

**Comment by Zylann** [comment]
Oh, I realize it might just be export... for some reason I didnt get it for import, that should be added.

**Comment by Muzz** [comment]
Aha! that makes more sense. 

Thanks!

**Comment by Zylann** [comment]
Implemented in 01b3f5ab056283714836d0e4bac632cc0fdcdd3f

I changed the issue title, since internal EXR support is an existing issue https://github.com/Zylann/godot_heightmap_plugin/issues/34
