### ISSUE TITLE
Godot eventually crashes after a lot of edits

### ISSUE THREAD

**Issue by Zylann** [Zylann/godot_heightmap_plugin#169]
**Describe the bug**
Godot crashes with this kind of error:
```
`all allocations are in use`
```
While barely occupying 400 Mb of RAM.

**To Reproduce**
Just paint in a lot of strokes, with the largest brush size. After about 30 seconds of spamming, it eventually crashes. It may be quicker with a texture brush on a terrain using the `ARRAY` shader, as two images are edited at once.

**Expected behavior**
Godot should not crash, as long as memory is still obviously available.
Eventually, edits data should be dumped to disk.

**Environment**
- OS: Windows 10
- Godot version: 3.2.2 beta3
- Plugin version: 1.2.2 dev
- Renderer used: GLES3

---------

This happens probably because when the brush is used, it backs up many chunks of 16x16 pixels in every area it modifies, for undo/redo to work. With a brush of 200x200, that means about 150 chunks. In a stroke, it could add up to 500. In a 2-texture edition brush, 1000. Repeated 65 times, we easily get over 65536 small `Image` objects. Add to this all arrays that existed before that.

The underlying issue cannot be fixed by this plugin, it's a Godot issue.
It could be https://github.com/godotengine/godot/issues/18094.

Meanwhile, a workaround would be to dump all these chunks to disk everytime a painting operation completes, which might be relatively slow if there are lots of small chunks to save (especially on Windows, where file I/O is relatively slow when many files are touched). A helper class to achieve this already exists in the plugin (used to backup full terrain changes so far).
This should be improved anyways because you could still run out of memory, just after a much longer time.

**Comment by Calinou** [comment]
Could the undo buffer data size be limited to avoid going over the limit of PoolByteArrays?

**Comment by Zylann** [comment]
@Calinou I use Godot's editor undo functionality, that's Godot's call :shrug: I wish it could automatically dump to disk itself, but it doesn't.
All the plugin can do is either to increase tile size so there are fewer of them, and dump heavy data to disk while storing an index in undo data.

**Comment by Zylann** [comment]
Note: I still use `PoolVector2Array` in the undo data to store tile positions. That will still cause the crash to happen unfortunately, so I'll be constrained to untype it and use `Array` instead :/

**Comment by Zylann** [comment]
That should be worked around by 4a092f1eead9b436efa21e40eec25b4c91235622
