### ISSUE TITLE
Normalmap resolution different from PNG import

### ISSUE THREAD

**Issue by tavurth** [Zylann/godot_heightmap_plugin#181]
**Describe the bug**
I have exported some high resolution tiles from World Machine, but when imported as a terrain they appear stepped, which appears to be a reduction of the texture size.

**To Reproduce**
1) Import heightmap
2) Lossy normals are generated

[Example project](https://github.com/tavurth/terrain-heightmap-issue)

**Expected behavior**
A smooth gradient between the normals, based on the original PNG import.

**Screenshots**
<img width="400px" alt="Screenshot 2020-07-13 at 15 41 25" src="https://user-images.githubusercontent.com/100964/87291629-52adc780-c51f-11ea-92f2-17be6edf0f36.png">

<img src="https://user-images.githubusercontent.com/100964/87291735-7bce5800-c51f-11ea-81d2-ec42575fd10a.png" width="300px" />

<img src="https://github.com/tavurth/terrain-heightmap-issue/blob/a59428e1c8212f1b5b28f999c0043c3aa6518f37/terrain/normal.png?raw=true" width="300px" />

**Environment**
<img width="329" alt="Screenshot 2020-07-13 at 15 45 17" src="https://user-images.githubusercontent.com/100964/87291968-da93d180-c51f-11ea-81a5-b065cb3e18df.png">

<img width="607" alt="Screenshot 2020-07-13 at 15 45 34" src="https://user-images.githubusercontent.com/100964/87292004-e5e6fd00-c51f-11ea-979a-1c174f8a7890.png">

**Plugin version**
From asset store

**Comment by tavurth** [comment]
I also tried converting the heightmap from black and white to red color, same as the exports from this plugin, but no luck there.

**Comment by Calinou** [comment]
Godot limits PNG textures' depth to 8-bit upon import. Use Radiance HDR (`.hdr`) or OpenEXR (`.exr`) for HDR textures instead.

**Comment by tavurth** [comment]
Hi @Calinou!

I changed the type to .exr on export, and also updated the plugin to the [latest version](https://github.com/Zylann/godot_heightmap_plugin/commit/79d179ebbcae2931f58975c25c44438506662854).

Now the terrain generates a flat normalmap however.

I've [updated my example repo](https://github.com/tavurth/terrain-heightmap-issue/commit/ca5dce7bd7834c86626a743a7769efce7e932da4) with the changes.

Any ideas?

**Comment by Zylann** [comment]
I had a look at your exr file from your commit, and I notice two things:
- When I open it with RenderDoc, I see it's completely black and all pixels have a value of (0, 0, 0, 1).
- It's a 32-bit RGBA float image, although I hope it doesn't pose any problem for Godot to open (and should be converted by the plugin into monochrome 16-bit float anyways).

**Comment by tavurth** [comment]
@Zylann Hi, thanks for taking a look. When I opened it in the OSX preview it seemed OK (after `brew install openexr`)

It's the OpenEXR format which is exported from [World Machine](https://www.world-machine.com/), I'll take another look and see if I can fix the export somehow.

Thank you!

**Comment by tavurth** [comment]
Sadly these are my only export options:

<img width="300" alt="Screenshot 2020-07-13 at 18 15 38" src="https://user-images.githubusercontent.com/100964/87304681-e8a01d00-c534-11ea-8c83-73486e77b25b.png">

After downloading the EXR file again from github, it seems to still function correctly for me. It looks like this:
<img width="300" alt="Screenshot 2020-07-13 at 18 17 46" src="https://user-images.githubusercontent.com/100964/87304833-28ff9b00-c535-11ea-822a-04f994d33d94.png">

Perhaps there is some issue with the EXR format exported by World Machine?

**Comment by Zylann** [comment]
> Edit: When you mention the file should not be added to project, does that mean I can remove it after godot_heightmap_plugin has imported everything? Useful to know if so!

Yes, and you dont even have to put it there in the first place. The import dialog should allow you to select a file anywhere in your computer.

So indeed, with Gimp I can see the shade. I don't know why RenderDoc fails like that.

I analyzed your heightmap and despite there being a shade, the range of that is only `0.1521`. The plugin imports EXR images at real range (not in 0..1), which means `0.1521` of height difference across the whole terrain is too small for you to notice any slope, so it will look flat.
Is there an option in WorldMachine to not normalize the height?

**Comment by tavurth** [comment]
> In the meantime you could use RAW as export format so you can use that option.

Thank you! With the RAW export it's working correctly:

<img width="1136" alt="Screenshot 2020-07-13 at 19 32 12" src="https://user-images.githubusercontent.com/100964/87311937-a4664a00-c53f-11ea-8fbe-5a145050c7f7.png">

I took a look around World Machine but couldn't find much in the way of height limitation for the exported EXR, perhaps it's there but I'm not too familiar with it yet.

I've updated my example repository including the raw file (to keep consistency with this repo), and so others can use it as an example.

Thank you again! 
Loving the CLOD terrain mapping, I wrote [an implementation](https://github.com/tavurth/clod-terrain) of it in WebGL a long time ago, and was very happy to see it in action here!

**Comment by Thyrux** [comment]
Hello!
I was about to report the same issue until I stumbled upon this thread on the last second. Similar thing happens on Unreal Engine 4, too, with PNG-format heightmaps. Each time level is loaded, landscape is blocky, but only for a few moments and then it will be smoothed out automatically. I assume there are some kind of "smoothing groups" or a shader of a sort that does the trick on UE4, which GHP is perhaps missing at the moment?
<img src="https://user-images.githubusercontent.com/27519308/92974219-67aac680-f48e-11ea-8890-fd7ef7d24dc7.jpeg" width="300" height="200" />Blocky landscape (16-bit)
<img src="https://user-images.githubusercontent.com/27519308/92974220-68dbf380-f48e-11ea-8fc2-c019c6a59b6e.png" width="300" height="200" />Random heightmap from internet (8-bit)
[Archive with few example heightmaps](https://github.com/Zylann/godot_heightmap_plugin/files/5211600/Exampliary.heightmaps.zip).
