### ISSUE TITLE
Map Scale value below 1 (axis does not matter) shows error in console, terrain still works

### ISSUE THREAD

**Issue by MJacred** [Zylann/godot_heightmap_plugin#184]
**Describe the bug**
HTerrain still works, but errors are printed to console, if HTerrain node has a map_scale value of less than 1.

Error:
```
 scene/3d/spatial.cpp:268 - Condition "!is_inside_tree()" is true. Returned: Transform()
```

**To Reproduce**
1. Create scene
2. Add new HTerrain node
3. Change Map Scale value for e.g. the x-axis to any value below 1, e.g. `0.5`
4. save scene
5. See error

Having a Data Directory set (or even filled with splatmap & Co.) makes no difference.

**Expected behavior**
No Errors printed to Console

**Environment**
- OS: Ubuntu 18.04
- Graphics card: GeForce GTX 970
- Godot version: 3.2.2
- Plugin version: 709f0467313cd0c6c9fce7360220634d50dd1b62
- Renderer used: GLES3

**Comment by Zylann** [comment]
Are you sure this originated from this plugin in the end?

**Comment by MJacred** [comment]
Yes, I deactivated the other plugins. Even deleted my scenes and restarted the editor. And then played with the scaling values and saving the new test scene with just one terrain.

**Comment by Zylann** [comment]
Looks like another error that I'm unable to pinpoint because the GDScript debugger just doesn't stop at all... sigh

**Comment by Zylann** [comment]
I pushed a fix in f428fa7b7b5e84a12ff41dcb291efd68ba1cae02

**Comment by MJacred** [comment]
Is fixed, thanks for your remarkable work!

**Comment by MJacred** [comment]
re-opening, as it is fixed in master, but not yet in latest release, sorry

**Comment by Calinou** [comment]
@MJacred Issues are generally closed as soon as they're fixed in `master`. Otherwise, we'd have to wait months before being able to close any issue.

**Comment by Zylann** [comment]
I got the (admittedly strange) habit to use a tag instead of closing so that these issues would be given more visibility for people who are still using the assetlib version. Closing is also fine though, I guess.

**Comment by MJacred** [comment]
@Calinou: Well, that's why I originally closed the issue, but then I saw another open-but-fixed issue with that tag and deduced Zylann's habit. Therefore the re-open... And this repo only has a few open issues, so Zylann's habit does not feel misplaced. There are pro's and con's here. Decisions like this remind me of the struggle for variable naming...

I'll close it again...
