### ISSUE TITLE
Crash occurs when orthogonal camera is pointed at terrain 

### ISSUE THREAD

**Issue by tricheco** [Zylann/godot_heightmap_plugin#185]
**Describe the bug**
A crash occurs when an orthogonal camera is pointed at the terrain 

**To Reproduce**
1. Aim orthogonal camera at HTerrain node
2. Start scene

or clone: https://github.com/tricheco/repro_hterrain and start project.

**Environment**
- OS: Win 10
- Godot Engine v3.2.2.stable.mono.official - https://godotengine.org
- OpenGL ES 3.0 Renderer: GeForce RTX 2080 Ti/PCIe/SSE2
- Plugin version: 1.3.2

**Comment by Zylann** [comment]
Should be fixed by ae017ea3ab12a94a301bf63bd8c9762ccc8eb176

**Comment by tricheco** [comment]
Wow, thanks! I will try it out soon. Thanks man!

**Comment by tricheco** [comment]
Confirming the problem is not occurring anymore.
