### ISSUE TITLE
"Terrain data is null, can't update detail layer completely" when changing "View Distance" of layer

### ISSUE THREAD

**Issue by tricheco** [Zylann/godot_heightmap_plugin#186]
**Describe the bug**
When adding a detail layer, changing the view distance of any layer causes an error when saving: "hterrain_detail_layer.gd: Terrain data is null, can't update detail layer completely"

**To Reproduce**
1. Add HTerrain
2. Add HTerrainLayer
3. Change View Distance on HTerrainLayer to anything other than the default
4. Save. 
5. Error: "hterrain_detail_layer.gd: Terrain data is null, can't update detail layer completely" shows in Output.
6. Error disappears and save is successful if "View Distance" is reverted to default.

**Expected behavior**
No error should appear, save should be successful

**Environment**
- OS: Win 10
- Godot Engine v3.2.2.stable.mono.official - https://godotengine.org
- OpenGL ES 3.0 Renderer: GeForce RTX 2080 Ti/PCIe/SSE2
- Plugin version: 1.3.2

**Comment by Zylann** [comment]
Should be fixed by c98fd5af1525f03234af8141c07ebbf2eecd4b07

**Comment by tricheco** [comment]
Thanks, I appreciate, will try soon!

**Comment by tricheco** [comment]
Confirming the problem is not occurring anymore.
