### ISSUE TITLE
How to use "Layer index" on HTerrainDetailLayer

### ISSUE THREAD

**Issue by carrascomj** [Zylann/godot_heightmap_plugin#187]
Hi,

I am using the grass detail feature. For the first map, it works fine, correctly generating the grass ("Layer index" 0). However, when I want to add another map (Map1), it is not painting anything ("Layer index" 1).

I guess that the brush is using the layer 0 to paint (?). How do I paint on layer 1?

[Here](https://github.com/Zylann/godot_heightmap_plugin/files/5017673/some_terrain.hterrain.gz) you have the terrain I am using, maybe that helps.

**Comment by Zylann** [comment]
Your archive only contains a file named `some_terrain.hterrain` which is a binary file that I have no clue what it is.

Internally, detail maps are large black and white textures covering the whole terrain, telling where grass is. There can be multiple of such textures, also called "layers".
`layer_index` chooses which of the textures the detail layer node will use. By default, it automatically selects the next one, and if it doesn't exist it gets created. If you set it to the same index as another layer, it will produce grass at the same spots.

Adding a second detail layer should have just worked. I see a second texture is created, but it doesnt appear to work properly.

**Comment by Zylann** [comment]
Indeed, was something stupid. Should be fixed in c98fd5af1525f03234af8141c07ebbf2eecd4b07

**Comment by carrascomj** [comment]
Now it is working perfectly fine, thank you so much for the quick fix!
