### ISSUE TITLE
Collision does not match visual representation

### ISSUE THREAD

**Issue by pol3waf** [Zylann/godot_heightmap_plugin#194]
The way my player object collides with the terrain does not match the visual representation.

### How to reproduce:
* Set Map Scale to 4x4x4 (edit: also happens with 1x1x1 size the important things is that slopes are steep enough)
* As colliding object I used a KinematicBody with 
  * safe margin = 0.1
  * sphere as CollisionShape with
    * radius = 1
    * margin = 0.1

The following screenshot illustrates the problem when the colliding object submerges into the terrain:
![clipping_problem_clipped](https://user-images.githubusercontent.com/3944892/90989191-0c756a80-e599-11ea-941c-ff8b4d5bc7fc.png)

The issue can also happen in the opposite direction: The colliding object hovers much to high above the terrain.

**Comment by Zylann** [comment]
Please fill the issue template. Someone reported the same issue recently: https://github.com/Zylann/godot_heightmap_plugin/issues/189

**Comment by pol3waf** [comment]
Sorry, I just looked for open issues and not closed ones. My bad.
I will try the recent master tomorrow. Thanks for the help!

**Comment by pol3waf** [comment]
Sorry that it took so long for me to confirm. The fixes in version 1.3.4 work great! Thanks!
