### ISSUE TITLE
How can I use the Procedural Generation example Script?

### ISSUE THREAD

**Issue by elliotrpage** [Zylann/godot_heightmap_plugin#195]
Hello,

Thank you for writing this helpful tool. Apologies for what is likely a basic question, but how do I use the Procedural Generation Script?

I have created a Spatial Node Scene and copied the example script into the GDScript attached to the Node. My assumption was that I would run the Scene (using F6) and a terrain node would be created and attached in the tree (due to the add_child call) however this assumption appears to be entirely wrong as nothing happens. 
No errors appear in the debugger when I run the Scene and I added some basic print commands to the script to see if it was getting caught anywhere but it runs through the whole function when run.

Again, apologies if I am missing something basic!

Yours,
Elliot

**Comment by Zylann** [comment]
Did you place a camera in the scene to actually see that terrain? If all you have is the spatial node, then by default Godot will look straight from the origin, and the terrain might have generated above, out of sight.

Try adding a camera (which you make current in the inspector), place it about 100 units above 0, increase its far clip to 1000 and make it look down, you should see something appear.

**Comment by elliotrpage** [comment]
Thank you very much! This has done the trick and I can see the terrain when I run the Scene. 

The one step I was hoping for (but may be incorrect in assuming this would work) is that the generated terrain would appear in the Editor itself as a Node so I could save it and edit/ use elsewhere. 
Would I need to turn the procgen script into a "tool" instead and run it within the editor?

Many Thanks,
Elliot

**Comment by Zylann** [comment]
You could make it tool, but you could also use `ResourceSaver.save()` on the data resource.

**Comment by elliotrpage** [comment]
Thanks, I'll give that a go. 
I've been using the Terrain Generator in-editor but (unless I am missing something) this does not provide the programmatic texture application that is present within the ProcGen script - I'm trying to spit out lots of individual terrain nodes so I can pick the ones I like and use these for individual levels. 

Apologies, I should have provided more detail at the start!

**Comment by elliotrpage** [comment]
I think I got it! I needed to `terrain.set_owner()` in the script, like described in your answer to this other question! 
https://godotengine.org/qa/15486/create-nodes-in-the-editor-from-script
