### ISSUE TITLE
Bug for version Godot 3.1

### ISSUE THREAD

**Issue by NothingSoftwares** [Zylann/godot_heightmap_plugin#196]
So the bug stems from what seems to be a "syntax" issue in GDscript. Now I did install it correctly from the asset library but for some reason the plugin.gd file in tools seem to stop the engine from running the plugin and the output tab outputs this: 

Godot Engine v3.1.stable.official (c) 2007-2019 Juan Linietsky, Ariel Manzur & Godot Contributors.
 res://addons/zylann.hterrain/hterrain.gd:22 - Parse Error: Expected constant expression
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR
 res://addons/zylann.hterrain/tools/plugin.gd:5 - Parse Error: Could not fully preload the script, possible cyclic reference or compilation error. Use 'load()' instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR
 res://addons/zylann.hterrain/hterrain.gd:22 - Parse Error: Expected constant expression
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR
  does not have a library for the current platform

To reproduce the bug just install Godot 3.1 stable and install the hterrain plugin. Simply try to turn the plugin on and you will get the error. From my previous experiences with Godot and your plugin I have never encountered the bug so can you please fix the bug?

**Comment by Zylann** [comment]
Apparently Godot 3.1 doesn't support the presence of other constants within the declaration of a constant.

i.e this doesn't work:
```gdscript
const SHADER_CLASSIC4 = "Classic4"
const SHADER_CLASSIC4_LITE = "Classic4Lite"
const SHADER_LOW_POLY = "LowPoly"
const SHADER_ARRAY = "Array"
const SHADER_CUSTOM = "Custom"

const MIN_MAP_SCALE = 0.01

const _SHADER_TYPE_HINT_STRING = str(
	SHADER_CLASSIC4, ",",
	SHADER_CLASSIC4_LITE, ",",
	SHADER_LOW_POLY, ",",
	SHADER_ARRAY, ",",
	SHADER_CUSTOM
)
```

But this works:

```gdscript
const _SHADER_TYPE_HINT_STRING = str(
	"Classic4", ",",
	"Classic4Lite", ",",
	"LowPoly", ",",
	"Array", ",",
	"Custom"
)
```

I don't know if that's the only place where it fails though.

**Comment by Zylann** [comment]
Just pushed a fix.
