### ISSUE TITLE
Linux library has incorrect name.

### ISSUE THREAD

**Issue by kubajz22** [Zylann/godot_heightmap_plugin#200]
**Describe the bug**
The prebuilt binary for linux is named "libhterrain_native.so" while the engine expects it to be just "hterrain_native.so". This causes the plugin to not work properly.

**Fix**
Simply renaming the file to "hterrain_native.so" fixes the problem.

**Comment by Zylann** [comment]
Just changed it in https://github.com/Zylann/godot_heightmap_plugin/commit/d36268375d7add119eb681305152497a13006629
