### ISSUE TITLE
Texture tiling reduction

### ISSUE THREAD

**Issue by kubajz22** [Zylann/godot_heightmap_plugin#202]
**Is your feature request related to a problem? Please describe.**
First of all, I really like your plugin and I want to use it in my game I'm working on. There's one thing that's bugging me though and as you've probably already figured out from the title it's the almost unavoidable visible texture tiling. I saw a couple videos on YouTube where people used a noise texture blended with the albedo to alter the color and hide the tiling in Unreal engine. I don't know if something like this is even possible with the Classic4 shader but if so, it would be awesome to have this option. I would try to make something myself but I've never written a shader and honestly can't understand the language well enough yet.

**Describe the solution you'd like**
An option in the editor where you could specify a noise texture which would be blended with the albedo of the terrain.

**Comment by Zylann** [comment]
It sounds possible however it comes at a high cost, depending on the graphics card your game is targeted at.
Otherwise tiling can be relatively well hidden with stuff placed on top of the ground, and is usually a mild detail when considering everything else that needs to occur in a game (I've noticed tiling in many games without it being a showstopper in any way)

**Comment by kubajz22** [comment]
That doesn't look bad.

**Comment by Zylann** [comment]
I'm trying to implement this with normal maps but because it involves rotation it then requires to also rotate the normal map, and I'm quite lost right now in how to find the correct combination because right now my shading keeps facing the wrong way

**Comment by Zylann** [comment]
I managed to make it work with normals.
I looked at the performance impact with the `Classic4` shader:
- Tiling reduction enabled: 1400 fps
- Tiling reduction disabled: 1600 fps

**Comment by Calinou** [comment]
@Zylann Comparing in terms of frame times (mspf) is more meaningful than FPS :slightly_smiling_face:

**Comment by Zylann** [comment]
I added the feature to `Classic4` and `Classic4Lite` shaders https://github.com/Zylann/godot_heightmap_plugin/blob/master/addons/zylann.hterrain/doc/main.md#tiling-reduction

**Comment by kubajz22** [comment]
I've noticed that some textures still produce repetitive artifacts, I'll try to tweak the code a bit when I have some time. Maybe I'll be able to come up with something.

**Comment by Zylann** [comment]
Yeah it's by no means a perfect solution. It only attenuates the effect, which is hard to completely get rid of with only two texture fetches. You can get even more randomness with more fetches but it may come at an even greater cost.
