### ISSUE TITLE
Terrain Shader expects DirectX style normal maps.

### ISSUE THREAD

**Issue by GoldenThumbs** [Zylann/godot_heightmap_plugin#203]
The Classic4 shader seems to expect normal maps with the "DirectX" style of orientation, with green channel representing the "down" vector, while Godot usually uses the OpenGL style of orientation (green being up). This could cause some confusion to users. Normal maps are already a sort of confusing topic for a number of people, and the requirement to have two different styles of tangent normal maps in one project will just lead to further confusion

**To Reproduce**
1. Create and setup a height map terrain node.
2. Use a OpenGL style normal map on a terrain material texture slot.

**Expected behavior**
Terrain to be correctly lit including the normal map information

**Screenshots**
Terrain being lit via the same OpenGL style normal map as the plane hovering slightly above.
![image](https://user-images.githubusercontent.com/24837412/94882619-1dce5400-042e-11eb-9a91-5f23b95c74db.png)

Terrain now being lit by a similar normal map with the green channel inverted (making it a DirectX style normal map)
![image](https://user-images.githubusercontent.com/24837412/94882693-4e15f280-042e-11eb-9939-25c01d86833d.png)

**Environment**
- OS: Windows 10
- GeForce GTX 1660 Ti
- Godot version v3.2.3
- Plugin version 1.3.4
- Renderer used: GLES3

Not a hugely important issue, nor a hard one to fix (could just invert the green channel in the shader) but I felt it was worth pointing out

**Comment by Zylann** [comment]
That's unfortunate, I was confused myself. I did the tests with normalmaps from CC0textures, it's not indicated anywhere and here we are^^"
As you can see in shaders I left comments about having to negate channels not being sure why, so maybe that's it...
I would need a normalmap which is certified to be OpenGL-style in order to fix this.

**Comment by Zylann** [comment]
Should be fixed in 04a739f1adb0475176a18c29f473ede2a0a1d4b2

**Comment by GoldenThumbs** [comment]
> 
> 
> That's unfortunate, I was confused myself. I did the tests with normalmaps from CC0textures, it's not indicated anywhere and here we are^^"
> As you can see in shaders I left comments about having to negate channels not being sure why, so maybe that's it... I'm surprised nobody found this earlier.
> I would need a normalmap which is certified to be OpenGL-style in order to fix this. I suppose this one is correct?
> ![debug_normalmap](https://user-images.githubusercontent.com/1311555/94910343-8522ed00-049c-11eb-944a-8f7b1c151db8.png)
> 
> Edit: actually when I read my shader, I'm not even negating anything. I unpack RGB as XYZ as it comes and pass it to the normal formula, so that's even more confusing now Oo

That should be correct, yes. As to why it's like this without there being any particular change being done in the shader to make it so, my *guess* would be how Godot order's it matrices, but I haven't looked into that at all.
