### ISSUE TITLE
Linux - When trying to use the plugin, the output box spams errors and nothing actually happens

### ISSUE THREAD

**Issue by Dragon20C** [Zylann/godot_heightmap_plugin#204]
**Describe the bug**
--When I installed the plugin on my linux system it installs correctly but when I try to actually change and add the terrain it doesnt do anything it spits out errors in the output box

**To Reproduce**
--Simply install the plugin and enable it

ERRORS:

errors messages: drivers/unix/file_access_unix.cpp:278 - Condition "!p_src" is true.
 drivers/unix/file_access_unix.cpp:278 - Condition "!p_src" is true.
 res://addons/zylann.hterrain/native/factory.gd:27 - Attempt to call function 'new' in base 'NativeScript' on a null instance.
 res://addons/zylann.hterrain/hterrain_brush.gd:161 - Invalid call. Nonexistent function 'generate_gaussian_brush' in base 'Nil'.
 Another resource is loaded from path 'res://addons/zylann.hterrain/hterrain.gd' (possible cyclic resource inclusion).
 modules/gdscript/gdscript.cpp:576 - Condition "!p_keep_state && has_instances" is true. Returned: ERR_ALREADY_IN_USE
![GodotERRORS]

**Expected behavior**
To change the terrain and textures but does nothing instead

**Screenshots**
(https://user-images.githubusercontent.com/15175043/95084252-8874dd80-0715-11eb-9bf1-54fd077cca25.png)

**Environment**
- OS: Manjaro KDE Linux - Arch based
- Graphics card: GTX 1650
- Godot version: 3.2.2
- Plugin version: 1.3.4
- Renderer used:GLES3

**Comment by Zylann** [comment]
Looks like part of the log is missing, errors before those you posted might have happened.
Try the master branch, there was an issue about the linux library not being registered properly: https://github.com/Zylann/godot_heightmap_plugin/issues/200

**Comment by kubajz22** [comment]
I was getting similar messages with the old version of the plugin as well. Just use the master and it should work fine.

**Comment by Dragon20C** [comment]
will try the master when I get the chance.

**Comment by Dragon20C** [comment]
Okay I have tried the master on godot 3.2.2 issues still exist on godot 3.2.3 I can change the hight map but textures seem to not apply, will do more testing to see.

**Comment by Dragon20C** [comment]
Okay seems to be working on the latest version of godot but 3.2.2 seems to not work
