### ISSUE TITLE
Terrain details are not visible when I use the instance mesh property

### ISSUE THREAD

**Issue by landen5** [Zylann/godot_heightmap_plugin#205]
**Describe the bug**
Terrain details are not visible when I use the instance mesh property. When I am in the editor view, the grass quads are visible with a texture displayed. After clicking play, the detail layer (grass) isn't displayed. I only encounter this problem when I choose an instance mesh for the HTerrainDetailLayer. 

**Expected behavior**
I expected the terrain detail layer to also be visible when I launch the game, not just in the editor view. 

**Screenshots**
![screenshot1](https://user-images.githubusercontent.com/35053801/95114765-489ffd00-06f9-11eb-9406-575dacef0a14.PNG)
![screenshot2](https://user-images.githubusercontent.com/35053801/95114767-49d12a00-06f9-11eb-9d41-0a54777a0036.PNG)

**Environment**
- Windows 10
- GeForce GTX 1060 6GB
- 3.2 (I encounter the same problem on 3.2.3)
- Godot Asset Store (I encounter the same problem with the GitHub version)
- GLES3

I am not sure if this is a bug or just me not understanding how to use this plugin.

**Comment by Zylann** [comment]
Just tried to reproduce this in a scene where I already had some grass, but it worked fine.
Is the grass still visible in editor after you restart the editor?

**Comment by Zylann** [comment]
Note: there is this thing with Godot that might be confusing:
If you JUST added the detail layer, even if you save the scene, Godot STILL hasn't *imported it*. So when the game starts, it doesnt load the layer because it was never imported.
But if you unfocus and refocus the editor, you should see it import something. Then, on second launch, the grass should be visible. That's what happen on my side at least.

**Comment by landen5** [comment]
After I restart the editor, the grass is no longer visible. 

Even when I make sure Godot properly imports it, it is still not visible when I launch. 

To reproduce, just do the basic setup described in the documentation. I encounter the same issue on different projects so I know that it isn't project-specific. 

I should also note that I only encounter this problem when I use an instance mesh. If I don't use an instance mesh, it works properly. 

[test_project.zip](https://github.com/Zylann/godot_heightmap_plugin/files/5329543/test_project.zip)

**Comment by Zylann** [comment]
Ok so you might encounter another issue than the one I just found.
I wonder what's special about instance meshes here...

**Comment by Zylann** [comment]
When you load back Godot, is the grass still not showing up if you select the terrain node? (due to Godot limitations LOD doesn't know where the camera is if the plugin doesnt get inputs from where you have the node selected).

**Comment by landen5** [comment]
Yes, when I load back into the Godot, the grass is still not visible when I select the terrain node.

**Comment by Zylann** [comment]
Looks like it only happens because `density` was left to its default value: Godot only SETS the property if it's not default, and looks like in that case it causes a race condition.
But if I try to change density while it is broken it logs errors so something went wrong silently before anyways.

**Comment by kubajz22** [comment]
I've encountered this issue before, it sometimes even floods the whole terrain with the detail. Those meshes that don't show up for the first time never rendered no matter what I did. You have to delete the layer and create a new one.

**Comment by Zylann** [comment]
You can leave your scene untouched, this should fix it 150ee3dc97ec5fda9258baf591c942adff6afc23
