### ISSUE TITLE
Allow setting the collision mask/layer in the inspector

### ISSUE THREAD

**Issue by Demindiro** [Zylann/godot_heightmap_plugin#206]
**Is your feature request related to a problem? Please describe.**
It seems there is no convenient way to set the collision layer/mask.

**Describe the solution you'd like**
Some way to set it in the inspector would be nice (and perhaps via script too).

**Describe alternatives you've considered**
I'm currently setting the collision bit via a script.
<details><summary>Script</summary>

```gdscript
func _ready()
	# ...
	call_deferred("_set_terrain_collision_bit")

func _set_terrain_collision_bit():
	var rid = $HTerrain._collider._body_rid
	# $HTerrain.set_collision_layer(bits) would be cleaner
	PhysicsServer.body_set_collision_layer(rid, 1 | Global.COLLISION_MASK_TERRAIN)
	PhysicsServer.body_set_collision_mask(rid, 1 | Global.COLLISION_MASK_TERRAIN)
```

</details>

**Additional context**
N/A

**Comment by Zylann** [comment]
Added in c5d176f2e4f4fb11fe17e9b6260d3baf6b10a363
