### ISSUE TITLE
Implement options to limit brush strokes to an angle range and a height range

### ISSUE THREAD

**Issue by Arnklit** [Zylann/godot_heightmap_plugin#211]
**Is your feature request related to a problem? Please describe.**
Very often when painting a terrain, you'll want certain textures to be applied to certain angles of the terrain or certain heights. Such as cliffs on steep angles or snow above a certain height.

**Describe the solution you'd like**
I'd imagine something like two check boxes in the brush settings. "Limit height" and "Limit angle" with a range slider next to each of them.

**Describe alternatives you've considered**
Not really sure there are any alternatives for this. You can of course manually change the splatmap outside godot, but that is very cumbersome.

**Additional context**
Mockup: 
![image](https://user-images.githubusercontent.com/4955051/98104324-321eca00-1e8e-11eb-8d13-2853db4ee3e2.png)
I made a test where I sampled the normal map blue channel during the stroke and used that to limit the angle. It was a bit rough but shows the idea.
https://youtu.be/NtLL3hhkHa8

**Comment by Arnklit** [comment]
Just realised the checkboxes are dumb and unnecessary. It would make more sense to just have the ranges default to the full range and when they were at the full range the test against angle or height could be skipped in the code.

**Comment by Zylann** [comment]
Do sliders have an option to have two handles?

**Comment by Arnklit** [comment]
Sorry never actually looked into it, and I haven't had time to try and make a functioning version of this myself. I think I just figured that would be a possibility since I'm used to Unity where there is a range slider that works that way. The mockup is just photo editing.

**Comment by Zylann** [comment]
What do you think?
![image](https://user-images.githubusercontent.com/1311555/100525974-92b6d380-31bc-11eb-8f0f-5eea9939d260.png)

**Comment by Zylann** [comment]
Available to test in the `gpu_painting` branch

**Comment by Arnklit** [comment]
Oh wow! That's great I'll have a look at it first thing tomorrow.

**Comment by Arnklit** [comment]
This is great Zylann! Been messing around with it all morning. But I think we need some kind of falloff on the angle to get nice results and not have it look pixelated based on the normals. Not sure what the best way of doing that is though. But I made a test here showing how much nicer it can look.

![image](https://user-images.githubusercontent.com/4955051/100539888-7608b300-3231-11eb-9b43-44c86e0947a0.png)

I did it like this, which is definitely buggy, because now you can't paint on all surfaces when the angle is set to full, so I did something wrong, but just so you can see the idea.

in splat4.shader

![image](https://user-images.githubusercontent.com/4955051/100539935-dc8dd100-3231-11eb-8b43-c6c9d1b519c7.png)

**Comment by Zylann** [comment]
Should the falloff be configurable or would a hardcoded value be ok?

**Comment by Arnklit** [comment]
I think a hardcoded value would be OK. Just something that tends to give nice results. And it would be a bit messy to add yet another control.

**Comment by Zylann** [comment]
Now available in 1.5
