### ISSUE TITLE
Loaded resource as image file, this will not work on export

### ISSUE THREAD

**Issue by Terragos** [Zylann/godot_heightmap_plugin#213]
Hello, I am new to posting on Github, am new to game dev, and am new to Godot. However, I have spent a lot of time of time on this game that you can see a preview for at Terragos.itch.io/cubit-crawler. Everything works fine when I am testing. When I export my project, it still works fine. The second I throw my project into a zip file, and extract it, the HTerrain node stops working almost entirely. 

If you would like to test what happens, download the current version posted online at the itch link, and go to settings, and press unlock all levels, and play the "Rising" level and just run towards the mountain range on any side and you just go straight through it (and die since you drown in the water behind it)) or get stuck in the mountain side.

Since discovering that my download does not work, I have noticed this warning text whenever I load a scene in my editor:
"core/image.cpp:1890 - Loaded resource as image file, this will not work on export: 'res://tdata/Rising/normal.png'. Instead, import the image file as an Image resource and load it normally as a resource.
core/image.cpp:1890 - Loaded resource as image file, this will not work on export: 'res://tdata/Rising/splat.png'. Instead, import the image file as an Image resource and load it normally as a resource.
core/image.cpp:1890 - Loaded resource as image file, this will not work on export: 'res://tdata/Rising/color.png'. Instead, import the image file as an Image resource and load it normally as a resource."

Any advice to make this plugin work would be appreciated. This may have been addressed somewhere else and I missed it, or it may just be a newb question. Thanks in advance for any help!

![Screenshot_2](https://user-images.githubusercontent.com/47040288/98485306-763e0180-21e3-11eb-9c67-c30fda84b372.png)

**Comment by Zylann** [comment]
This warning should not actually prevent the game from working, though https://github.com/godotengine/godot/issues/24222
Games were made with this plugin before while this warning was present (https://ahintoflime.itch.io/30-pictures).
Maybe it's a recent breakage I'm not aware of.

> When I export my project, it still works fine

Good?

> The second I throw my project into a zip file, and extract it, the HTerrain node stops working almost entirely.

What? Oo
I don't understand that part. You said just before your project worked fine after export, but I don't get why zipping has any bearing on it. If all you do is zip the exported game (a game that works!) and unzip it, the unzipped files should still work.

It's too late here for me to test now, but I might come back later.

**Comment by Terragos** [comment]
So what I thought was happening originally, was what you suggested about it working on my device but not others. So I tested zipping it and immediately unzipping it, and it would not work after unzipping it. I can try to post a screen recording shortly to demonstrate.

**Comment by Terragos** [comment]
[Errors.zip](https://github.com/Zylann/godot_heightmap_plugin/files/5511429/Errors.zip)

**Comment by Zylann** [comment]
In your video, you did not include `hterrain_native.dll` in the zip file.

**Comment by Terragos** [comment]
Oh no... I knew I was stupid. Thank you!
