### ISSUE TITLE
Terrain not saved/loaded in latest Godot 3.2.4 branch

### ISSUE THREAD

**Issue by capttheo** [Zylann/godot_heightmap_plugin#216]
**Describe the bug**
In recent Godot 3.2.4 branch, terrain not saved/loaded

I'm opening new issue, because it is introduced by recent Godot change.
In released 3.2.4 beta1 plugin works, but in current 3.2.4 branch its not.
I already bisected and it introduced by this commit in Godot, related to Reference: https://github.com/godotengine/godot/commit/1e9a774ac24ecbbec9b0aa4b903f3f1525f4d525 
Also this commit leads to some discussions of what was changed
https://github.com/godotengine/godot/pull/43049
https://github.com/godotengine/godot/pull/42323

**To Reproduce**
Build latest Godot 3.2.4 from 3.2 branch https://github.com/godotengine/godot/tree/3.2

When opening empty project with hterrain plugin enabled, there are following error messages:

`core\io\resource_loader.cpp:539 - Condition "p_format_loader.is_null()" is true.`
`It's not a reference to a valid ResourceFormatSaver object.`

When trying to open scene with actual HTerrain node, it is not loaded due to missing dependencies to res://path/data.hterrain
`No loader found for resource: res://path/data.hterrain`

When trying to save scene with new HTerrain node, nothing saved into folder.

**Screenshots**
![resourceloader](https://user-images.githubusercontent.com/72292300/98831839-24001900-244d-11eb-99d3-e0f668e447ed.png)

**Environment**
- OS: Windows 10
- Godot version 3.2.4 current (later than beta1)
- Plugin version - Latest (a0e10af)
- Renderer used: GLES3

**Comment by Zylann** [comment]
How can I fix this though?

**Comment by capttheo** [comment]
I'm not sure, just wanted you to know (after all it will break anyway at next engine release - should I report there too?). I have experience with EditorImportPlugin but not with ResourceFormatLoader and only started digging.

**Comment by Zylann** [comment]
It could be that custom resource loaders got broken by this, so it could be reported in Godot. I hope it's the only breakage that occured, though.

**Comment by Zylann** [comment]
I opened an issue. We'll have to see if there are other bugs once custom loaders get fixed.

**Comment by capttheo** [comment]
Thanks for your work on great plugin :) You did MRP faster than I could.

**Comment by capttheo** [comment]
Found another problem, this commit https://github.com/godotengine/godot/commit/8a02f221b468056345b7506a463a8c8b529bfb29 caused properties disappear from editor
![hterr](https://user-images.githubusercontent.com/72292300/99012970-8dbd1780-2560-11eb-8ab3-1f0cf514cf7d.png)

**Comment by Zylann** [comment]
Looks like the resource loader issue just got fixed in the 3.2 branch

**Comment by capttheo** [comment]
From simple testing, looks fine.
