### ISSUE TITLE
Splat16 cycles the layers when using undo or saving and loading the scene

### ISSUE THREAD

**Issue by Arnklit** [Zylann/godot_heightmap_plugin#223]
**Describe the bug**
Splat16's undo feature cycles the layers when using undo or saving and loading the scene

**To Reproduce**
Open the attached project, 
Try to paint on the terrain and undo,
Try to save and load.

**Repro project**
[RiverToolDemo.zip](https://github.com/Zylann/godot_heightmap_plugin/files/5694086/RiverToolDemo.zip)

**Comment by Zylann** [comment]
Should be fixed by 7c1c0e8bbf4276291b79c6e0401aa1eeeaebde10
