### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by Jummit** [Zylann/godot_heightmap_plugin#225]
This project currently has no license, which prevents me from using some of the code in my own project. I am working on a project with undo/redo of image manipulation, and would like to use the image_file_cache script. I would of course include the source and license.

**Comment by Zylann** [comment]
The license is here https://github.com/Zylann/godot_heightmap_plugin/blob/master/addons/zylann.hterrain/LICENSE.md

**Comment by Calinou** [comment]
> The license is inside the plugin https://github.com/Zylann/godot_heightmap_plugin/blob/master/addons/zylann.hterrain/LICENSE.md

I guess it could be copy-pasted outside the plugin directory so that GitHub can detect it.

**Comment by Jummit** [comment]
Oh, sorry. I missed that. While it would be nice if it would be placed in the root directory so Github is aware of it, it's not necessary.
