### ISSUE TITLE
Error when opening example project in Godot stable

### ISSUE THREAD

**Issue by gek169** [Zylann/godot_heightmap_plugin#227]
Unable to load addon script from path: 'res://addons/zylann.hterrain/tools/plugin.gd' There seems to be an error in the code, please check the syntax.

The error comes from the first preload:
const HTerrain = preload("../hterrain.gd")

The error talks about a cyclic reference.
![screenie20201223_111602](https://user-images.githubusercontent.com/6974902/103016590-47b88380-4510-11eb-9914-c4b25aecdf5a.png)

**Comment by Zylann** [comment]
There is no error in the code. Godot is bad at loading/importing some plugins for the first time, as posted here: https://github.com/godotengine/godot/issues/23937

Try restarting the project?

**Comment by Zylann** [comment]
It seems you downloaded this demo instead: https://github.com/Zylann/godot_hterrain_demo

Sorry, this one is outdated. The Godot Asset Library does not allow us to manage dependencies, so we have to copy manually plugins in their demos each time we do an update, and this one hasn't been updated in a while. It uses version 1.1 but now the version is 1.5, you should get it from here instead: https://godotengine.org/asset-library/asset/231

**Comment by Zylann** [comment]
I updated the demo project.

**Comment by gek169** [comment]
Ah. Thank you.
