### ISSUE TITLE
Error spam when game is running for a bit

### ISSUE THREAD

**Issue by Animus-Surge** [Zylann/godot_heightmap_plugin#230]
**Describe the bug**
Whenever my game has been running for... around three or four minutes, I get spammed with this error in the debug console:

```
E 0:02:07.145   getornull: Condition "!id_map.has(p_rid.get_data())" is true. Returned: __null
  <C++ Source>  ./core/rid.h:160 @ getornull()
```
I'm not sure what this is, or if this is an engine issue, so if I need to switch this over to the engine, I'll gladly do so.

**To Reproduce**
I don't really know, I guess create a terrain, edit it some, create a 3D player, then play the game for a few minutes.

**Expected behavior**
I don't want these errors to be spammed. I'm planning on adding a logging system so players can report issues that they have, and I don't want these errors to be spammed in any case.

**Screenshots**
I got none, sorry.

**Environment**
- OS: Windows 10
- Graphics card: Intel HD 4600 (integrated with a core i5-4760)
- Godot version: 3.2.3
- Plugin version: 1.5.1
- Renderer used: GLES3

**Comment by Zylann** [comment]
There isn't much I can do with this. The reported error is too cryptic, it could be a lot of different things, some not even related to the plugin.

Perhaps debugging the engine while having a breakpoint in `err_print` would give some insight, but even if we have it, the calling code might not necessarily be the culprit.

For example, I recently had the same error happening in the editor, and the cause was totally unrelated to my code, if you are curious about it: https://github.com/godotengine/godot/issues/44642
In your case maybe the cause is different, but without more insight it's hard to find out.

**Comment by Animus-Surge** [comment]
Sorry it took a while to respond, had stuff going on.

I think the issue is being logged by the game, because when I launch it from the command line, the exact same error appears. I think it has to do with the collisions, though, because I remember having a similar error on runtime when a mesh is used to generate `ConvexCollisionShape`s.

**Comment by Zylann** [comment]
Well I would need reliable reproduction steps still, or a project reliably producing it. I wasn't able to find it with my own tests.

**Comment by Animus-Surge** [comment]
Alright, I can try to send over a test project of mine. It usually happens when the player moves around, so I'll see about sending over a project either later today (us eastern) or tomorrow.

**Comment by tinmanjuggernaut** [comment]
It's an engine issue, not a heightmap issue.
You can read about it here:
https://github.com/godotengine/godot/issues/53374
The fix is coming here
https://github.com/godotengine/godot/pull/54650

**Comment by tinmanjuggernaut** [comment]
The fix has been merged into 3.x. Please try that branch. This ticket can be closed as is not a heightmap issue at all, it's an engine issue.

https://github.com/godotengine/godot/pull/54650

Also note, if your code calls VisualServer.free_rid() or PhysicsServer.free_rid() with invalid RIDs, your code can recreate this issue.

**Comment by Animus-Surge** [comment]
> This ticket can be closed as is not a heightmap issue at all, it's an engine issue.

Okay. Thank you for the info
