### ISSUE TITLE
Allow using the "Generate Terrain" feature on top of an existing terrain as a modifier

### ISSUE THREAD

**Issue by Arnklit** [Zylann/godot_heightmap_plugin#238]
**Is your feature request related to a problem? Please describe.**
Some times you want to add in more detail to the entire terrain or an erosion effect to the whole terrain, while maintaining the large shapes you've already sculpted.

**Describe the solution you'd like**
Rename the "Generate Terrain" to Generate/Modify Terrain" and have a checkbox as to whether you want to clear the old terrain or modify it.

**Describe alternatives you've considered**
I guess it could also be a separate function from the "Generate Terrain" window, but that seems more cumbersome, the "Generate Terrain" function seems to do everything needed, except it always overrides the old terrain.

**Additional context**
NA

**Comment by MJacred** [comment]
should be fixed by 277231c0084280ed1333a7d222bf047dda9803c0 (plus fix 99ad64627293f75855e127a359fc8f45972ccb0b)
