### ISSUE TITLE
Textures are not displayed correctly 

### ISSUE THREAD

**Issue by AurelienCaille** [Zylann/godot_heightmap_plugin#240]
**Describe the bug**
On editor launch and export somes textures are not displayed correctly.

**Screenshots**
What I see when opening the editor or export game:
![notgood](https://user-images.githubusercontent.com/22189681/105044830-779f6c00-5a67-11eb-99b2-a0531317497e.PNG)

But if I do any modification (even painting same texture) it show a correct display (only in editor, bug come back if I close then open again the editor)
![good](https://user-images.githubusercontent.com/22189681/105045212-f09ec380-5a67-11eb-9bd1-cb16a2dbac3d.PNG)

**Environment**
- OS: Windows 10
- Graphics card (GeForce GTX 1050 Ti/PCIe/SSE2)
- Godot version [e.g. 3.2.3]
- Plugin version (1.5.1)
- Renderer used: GLES3

**Comment by Zylann** [comment]
How are you reproducing this?

The only thing I can guess from the screenshot, is that you are using `MULTISPLAT16`, and what you are seeing are artifacts that sometimes occur with it. 
This shader cannot blend more than 4 textures at once in one pixel, so it has to ignore the 12 others and only blend the 4 highest weights. This works most of the time, but if you paint too many textures at equal weight in the same spot, it can cause artifacts like this.
