### ISSUE TITLE
Mistake in documentation - OpenGL convention

### ISSUE THREAD

**Issue by kubajz22** [Zylann/godot_heightmap_plugin#249]
**Describe the bug**
https://hterrain-plugin.readthedocs.io/en/latest/#normal-maps the Y is positive. This is an never ending battle I suppose..

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot/issues/46363.

**Comment by Zylann** [comment]
Y is positive toward what though? Either way, the image below is what I mean. It's too easy to mistake coordinate systems...

**Comment by Zylann** [comment]
Also I took that from here:
![image](https://user-images.githubusercontent.com/1311555/110222869-6e5e4780-7ecd-11eb-9cf7-a57bf4845be5.png)

So which way is right?

**Comment by Calinou** [comment]
> Godot does not actually use OpenGL convention for normal maps then?

It's definitely supposed to use OpenGL normal maps as far as I know, but maybe the way the terrain mesh is generated causes problems with that (incorrect binormals/tangents).

**Comment by Zylann** [comment]
> maybe the way the terrain mesh is generated causes problems with that

I'm not aware of a bug with this (I coded triplanar manually, it's not from SpatialMaterial), but you could open an issue if you found something

**Comment by kubajz22** [comment]
> Also I took that from here:
> https://docs.godotengine.org/en/stable/tutorials/3d/spatial_material.html#normal-map
> ![image](https://user-images.githubusercontent.com/1311555/110222869-6e5e4780-7ecd-11eb-9cf7-a57bf4845be5.png)
> 
> So which way is right?
> Godot does not actually use OpenGL convention _for normal maps_ then?

That documentation is wrong as well. I created an issue report a long time ago but nobody fixed it yet. I'll probably make a PR eventually.

**Comment by Calinou** [comment]
> That documentation is wrong as well. I created an issue report a long time ago but nobody fixed it yet. I'll probably make a PR eventually.

For reference, that was https://github.com/godotengine/godot-docs/issues/4555.

**Comment by MJacred** [comment]
the documentation is correct now, so the issue can be closed

**Comment by Calinou** [comment]
Closing per @MJacred's comment.
