### ISSUE TITLE
Add .tres/.res texture loading

### ISSUE THREAD

**Issue by mrjustaguy** [Zylann/godot_heightmap_plugin#250]
**Is your feature request related to a problem? Please describe.**
Currently, albedo texture also assumes the texture to be colored, this is not always the case. often times, in case of mono-color textures (textures that have only one color with different intensities) it is best to have the albedo texture be in black and white, so that in the editor you can use the same texture for several different materials, each with different color albedo applied to the texture.

Additionally, for those using Material Maker, it's way faster to drag the generated .tres as a material to use for texturing.

**Describe the solution you'd like**
Add a way to load .tres as an alternative to the current texture loading mechanism. That way users of Material Maker, or just simply anyone who prefers to make their materials as SpatialMaterial and then tossing them up into the editor has the ability to just do so.

**Describe alternatives you've considered**
I have considered adding a Color parameter for coloring the Albedo, however the speed & flexibility I haven't been able to think up of anything.

**Additional context**
I've been using Material Maker, to carefully create a Rock-Sand like texture, that when in Black and white, Appears rock like, however tinting the texture slightly yellow, gives it a very sandy look. Also, having multiple types of Dirt (darker and lighter types, with slightly different tints) with one Texture instead of half a dozen which can be done with tinting the albedo saves on space, significantly in extreme cases (I mean hey, every 4k texture less can be dozens of megabytes saved, saving both space and increasing loading & import times)

**Comment by Zylann** [comment]
> Currently, albedo texture also assumes the texture to be colored

Which albedo are you talking about? Albedo is used in several places for different purposes so I dont know which specific workflow you refer to. Nothing stops you to really just assign the same texture to multiple slots.

> Add a way to load .tres as an alternative to the current texture loading mechanism

It's not possible to drag materials directly like that, these materials don't work with a terrain system using splatmapping. If the burden comes from assigning them in the slots, if you use a common naming convention the tool is able to recognize files next to it and auto-assign all maps when loading the albedo.
Despite that, if you still want  to choose from a `.tres`, the tool can only pick the textures in it and won't actually use the material.

The plugin already has to support a number of variants to texturing and supporting even more is getting really complicated to maintain. I have never seen a terrain system using monochrome albedo textures, it's not a common use case. If you want to optimize stuff based on the assumption your albedo is monochrome, then it sounds like you have to do something yourself with a custom shader.

> every 4k texture less can be dozens of megabytes saved, saving both space and increasing loading & import times

That is true, and it might be possible to change the texture format to `RG` for the `albedo+roughness` slots, however the shader expects roughness to be in the alpha channel. That's as frustrating as it gets, but you still have to modify the shader if you want this. Godot doesn't have preprocessor macro support so it's too much effort to maintain this over all the plugin's shaders at the moment. I started experimenting with `VisualShader` nodes but work on this is far from finished.

**Comment by mrjustaguy** [comment]
The albedo texture that is loaded, there is no way to tint it, something that godot materials have the ability to do, and the idea was to just use that for that and for the general benefits, But I guess if it's not possible, yeah it boils down to separate issues and probably not worth the effort to implement workarounds due to complexity and/or niche use case of said issue solutions. As such I'm closing this
