### ISSUE TITLE
can this be used in a commercial game?

### ISSUE THREAD

**Issue by Lexi-kelly** [Zylann/godot_heightmap_plugin#256]
does the licence allow for this plugin's use in commercial games?
with credit of course.

**Comment by Calinou** [comment]
Yes, the MIT license allows commercial use and redistribution: https://github.com/Zylann/godot_heightmap_plugin/blob/master/LICENSE.md

**Comment by Gusher** [comment]
Oh wow, unbelievable, that's great!
