### ISSUE TITLE
Standalone Terrain Generator

### ISSUE THREAD

**Issue by tay10r** [Zylann/godot_heightmap_plugin#261]
Hello!

I had started working on a standalone terrain generator semi-specifically for this plugin, until I realized it has one embedded that I just didn't see the first few days of using it. Before I archive the code and begin working on something else, I figured I'd ask if you think this tool could use a separate app for design.

I didn't make it too terribly far, so it wouldn't be too much work to drop at this point. Here's a screenshot.

![Screenshot from 2021-05-07 20-15-46](https://user-images.githubusercontent.com/69982525/117521110-ae938200-af71-11eb-82f6-15fe93a885eb.png)

**Comment by Gusher** [comment]
Am very interested as standalone! Do you have this on github to follow progress?

**Comment by tay10r** [comment]
@Gusher thanks for showing interest! It's pretty elementary at this point but if you'd like to checkout the code so far then it's here: https://github.com/tay10r/terrain_generator

**Comment by Gusher** [comment]
Thanks alot.... if you got a discord or telegram channel to follow would be cool too..

**Comment by Zylann** [comment]
The builtin generator is a quick tool rather than a full-blown solution, so a dedicated tool still sounds valuable.

**Comment by tay10r** [comment]
@Gusher there should be a discord link now on the README, or just use [this one](https://discord.gg/m94UpRPJnB). It's still kind of early at this point but if you'd like to join then it's there. Thanks!
