### ISSUE TITLE
3D Render Layers

### ISSUE THREAD

**Issue by Dieviete** [Zylann/godot_heightmap_plugin#278]
First of all thank you for writing this awesome plugin. Is there a way to set the layers the terrain is drawn on? Apparently it is always drawn on layer 1 and I have not yet been able to change this.

**Comment by Zylann** [comment]
It needs to be exposed, shouldn't be hard. I almost forgot this feature existed^^"

**Comment by Dieviete** [comment]
Thank you for the quick reply! Could you point me into the right direction to expose it? As your plugin does not make use of the layer mask property of VisualInstance, the `set_layer_mask(int mask)` method cannot be used. I thought that maybe the `instance_set_layer_mask( RID instance, int mask )` method of VisualServer could be used but I am not sure how to implement it to change the render layers of the terrain.

**Comment by Dieviete** [comment]
Hey, sorry to bother you again, but could you give me a hint on how to change the layers? I am trying to use your plugin for a university project and it works really well, apart from changing the layers which I have not yet figured out.

**Comment by Zylann** [comment]
I added it in 3d6e6765e17d7b5b2450eb8334f505da6253999b, let me know if it works for you

**Comment by Dieviete** [comment]
Thank you very much! I will try tomorrow and let you know

**Comment by Dieviete** [comment]
Hey, Zylann! It works great, thank you very much!
