### ISSUE TITLE
Undo doesn't work on hterrain editing?

### ISSUE THREAD

**Issue by elvisish** [Zylann/godot_heightmap_plugin#280]
I've tried un-doing and nothing happens. Do I need to enable this somehow?

**Comment by Zylann** [comment]
I just tested sculpting a bit, undo works fine.
What steps are you following that leads undo to not work?

**Comment by elvisish** [comment]
I just installed it fresh, painted a couple of mountain bulges and pressed ctrl+z and nothing happens. I tried it several times but it just doesn’t seem to work.

**Comment by Zylann** [comment]
Do you see errors in the console?

**Comment by elvisish** [comment]
It seems to have started working now for some reason! If it happens again, I'll mention it here, I have no idea why it didn't work and why it does now!

**Comment by elvisish** [comment]
I imagine it was related to ‘emulate 3 burton mouse’ setting I had on, nothing to with hterrain!
