### ISSUE TITLE
Adding grass details causes huge performance drop

### ISSUE THREAD

**Issue by LimaneGaya** [Zylann/godot_heightmap_plugin#283]
**Describe the bug**
Adding a simple grass placeholder, without even adding grass texture or painting on terrain cause huge performance drop from 90fps to 25fps.
![Screenshot_20210917_234739](https://user-images.githubusercontent.com/36268750/133861911-77f43855-f5de-4c68-9069-545e4b5b67ec.png)

![Screenshot_20210917_234901](https://user-images.githubusercontent.com/36268750/133861946-525f94ed-4705-4681-be94-7460e7d5726b.png)

**To Reproduce**
clicking the add grass button.

**Environment**
- OS: Kubuntu 21.04
- Godot version 3.3.3
- Plugin version 34a02792d03a46197ec27292722e81f0d3b16ff9
- Renderer used: GLES3

**Comment by Calinou** [comment]
What graphcis card model do you have?

**Comment by LimaneGaya** [comment]
@Calinou it's and amd e1 apu. It's really low end but thought the performance decrease is more than what it should be.

**Comment by Zylann** [comment]
How big is that terrain? How far away did you set grass view distance? Can you see if something takes a lot of time in the profiler?

**Comment by LimaneGaya** [comment]
So tried to find the problem for the issue and it seemed to be the HTerrainDetailLayer was updating shader properties and calling other function not necessary when the grass is static. Tried to fix this and got noticeable performance gain.

![Screenshot_20210918_233008](https://user-images.githubusercontent.com/36268750/133910351-e39b871e-e088-4c93-9658-3abfa7703106.png)

**Comment by Zylann** [comment]
From the PR that's very likely just the editor being redrawing. Fixing this part would be an improvement though.
