### ISSUE TITLE
Heightmap collision generation via PhysicsServer causes game to freeze for over a minute

### ISSUE THREAD

**Issue by droc101** [Zylann/godot_heightmap_plugin#290]
**Describe the bug**
I'm not sure if this is the right place to put this, but when loading the scene in game with a large heightmap, the game freezes for multiple minutes. I have done some troubleshooting and believe that the line causing the issue is `PhysicsServer.shape_set_data(_shape_rid, shape_data)` in `hterrain_collider.gd`. The only modifications I made to the plugin was changing the maximum terrain size to 8193 (from 4097), and adding timers with OS.get_ticks_msec() to time functions for debugging.
 Again, I'm not sure if this is the correct place to put this, as it might be an issue with PhysicsServer or something like that. 
In case it matters, I am using the MultiSplat16 shader.

**To Reproduce**
I can't seem to reproduce the issue in other projects, but it might be possible to do so by creating complex terrain with a large size.

**Expected behavior**
The collision should not take over a minute to be added to the physics server.

**Environment**
- OS: Windows 10 21H1
- Graphics card AMD Radeon RX Vega 11 (Integrated GPU)
- Godot version 3.3
- Plugin version 1.5.2
- Renderer used: GLES3

**Comment by Calinou** [comment]
@droc101 Please upload a minimal reproduction project to make this easier to troubleshoot.

Also, try upgrading to 3.4 as it features many physics fixes and optimizations. Did you change any project settings such as the physics engine or the thread model?

**Comment by droc101** [comment]
I will try it with 3.4, I did change some graphics settings to make it perform better on my hardware, including changing to a multi threaded model. I will try to work on a reproduction project.

**Comment by Zireael07** [comment]
> changing to a multi threaded model

This most likely is your culprit.

**Comment by droc101** [comment]
Changing to 3.4 and Single-Safe thread model fixed all the issues! Thanks for the help.

**Comment by Calinou** [comment]
If using Bullet, this may be due to https://github.com/godotengine/godot/issues/30027.
