### ISSUE TITLE
Textures do not appear to respect 'Filter' import option

### ISSUE THREAD

**Issue by Bropocalypse** [Zylann/godot_heightmap_plugin#305]
When using low-res textures(IE, pixel art textures), the terrain does not appear to use them in a way that retains the sharpness of those pixels even when the image's import options are set correctly.

**To Reproduce**
Import a low-res texture with the 'Filter' flag disabled and use it in the terrain's textures.
**Expected behavior**
Sharp edges on those pixel textures.

**Environment**
Operating System: Kubuntu 20.04
Godot Engine v3.4.2.stable.official.45eaa2daf - https://godotengine.org
OpenGL ES 3.0 Renderer: NVIDIA GeForce GTX 1650/PCIe/SSE2
OpenGL ES Batching: ON
Plugin ver. 1.5.2

**Comment by Zylann** [comment]
Works for me here 🤔 
Can you give more details on how you get that problem?
![image](https://user-images.githubusercontent.com/1311555/152644697-cef6c6a3-c99c-4be7-be4c-9fcef259a9f0.png)

**Comment by Bropocalypse** [comment]
![image](https://user-images.githubusercontent.com/58696984/152647906-5294f078-0957-4b5d-a6b3-23c1088e33fb.png)

I dunno, it just looks like this. 

![image](https://user-images.githubusercontent.com/58696984/152647946-f092d7da-8833-4a45-9dce-27906e550fe5.png)

And the texture looks like this.

No other objects or scripts exist in the project other than the terrain and this single texture whose import settings have the filter disabled.

**Comment by Zylann** [comment]
Does the texture appear pixelated if you use it somewhere else?
Did you click "Reimport" after changing the option?

**Comment by Bropocalypse** [comment]
Oh, I see. I didn't realize that it created a new texture file unique to the terrain.
I was caught off-guard because I expected the terrain to respect the import settings of the image file. The import settings were set before I assigned the image to the terrain.

**Comment by Zylann** [comment]
Depends how you went here. You can go both ways: either set PNGs directly and in this case PNG import settings will be used. But if you went through the importing dialog (similar UI but a bit different), then it creates a second stage in which the images are packed into a single resaource.

**Comment by Bropocalypse** [comment]
Oh, I wasn't even aware that there was a way to set PNGs directly. I just followed the steps in the documentation for adding images to the brushes.
