### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by jkulawik** [Zylann/godot_heightmap_plugin#313]
I'm on the latest stable Godot version, 3.4.3 that is. Installing from the AssetLib (which uses the master branch, I presume) or installing the 1.5.2 branch manually both yield this message:
```
Unable to load addon script from path: 'res://addons/zylann.hterrain/tools/plugin.gd'.
This might be due to a code error in that script.
Disabling the addon at 'res://addons/zylann.hterrain/plugin.cfg' to prevent further errors.
```
I thought that the 3.4.x versions are supported? Did I download the wrong branch?

**Comment by Zylann** [comment]
Which errors? They should be shown in the console.
Did you try closing and reopening the project?

**Comment by jkulawik** [comment]
Oh ok, for some reason the errors didn't pop up and I had to open the console manually first.

It turned out I already had a class called `Map` and there was a conflict. I renamed my class to `Level` and the plugin seems to be working properly now. I used the AssetLib version.

**Comment by Zylann** [comment]
> It turned out I already had a class called Map and there was a conflict

Ouch...
And we still don't have namespaces in Godot. That's one thing they are for lol
Well I guess I could prefix everything in the module to prevent that from happening

**Comment by Zylann** [comment]
I just prefixed every internal class in the plugin, so if you use the master branch version you should be able to name your class Map.
