### ISSUE TITLE
"Load failed due to missing dependencies" for packed textures.

### ISSUE THREAD

**Issue by lucidpetal** [Zylann/godot_heightmap_plugin#319]
Hello,

I am using this plugin in a project and notice that the packed textures are not properly regenerated when they are not import folder is missing. All texture sets using the packed textures break. This means that every time the import folder is cleared, all texture sets must be recreated for all terrains instances. This is cumbersome.
A similar issue was already posted at the heightmap demo repository which contains even more detail, but was never replied to.
[https://github.com/Zylann/godot_hterrain_demo/issues/5](https://github.com/Zylann/godot_hterrain_demo/issues/5)

I think this happens because the plugin tries to load packed textures which are not yet generated by the importer.
If the .import packed textures are regenerated when the project is already open, then there seems to be no issue. The issue only occurs when the project is opened without the .import packed textures.

Godot version is 3.4. 

Steps to reproduce:
1. Create any project with a test heightmap.
2. Leave the project.
3. Remove the .import folder.
4. Open the project.

**Comment by Zylann** [comment]
That doesnt make sense though... it's not the plugin's job to decide *when* to reimport files that have no imported files associated anymore... it's Godot.
So if Godot is not calling again the packed texture importers, that would be a Godot problem.

**Comment by lucidpetal** [comment]
You are correct. 
Re-opening the project after the error works correctly. The bug lies within Godot itself. 
Thanks for response and great plugin.

**Comment by Zylann** [comment]
I'm currently attempting to make some changes to the plugin to make it load the *logic* properly so importers aren't messed up, however the UI of the plugin might still be buggy and require a restart
