### ISSUE TITLE
These weird artifacts

### ISSUE THREAD

**Issue by Axepecticle** [Zylann/godot_heightmap_plugin#328]
i'm having a problem with displaying of terrain. at a certain angle of light on the ground there are weirdly looking artifacts like on old LCD monitors. i guess this is the problem with shaders or smth.
![image_2022-07-09_180016599](https://user-images.githubusercontent.com/92867220/178113357-695993dd-8ebc-4e1c-8889-41929184a18a.png)

**Comment by Calinou** [comment]
This is likely caused by shadow acne. Try increasing shadow bias and/or normal bias in your lights' properties in the inspector.

**Comment by Axepecticle** [comment]
well, i just enabled the "reverse cull face" function and it worked :)
thx anyway!
