### ISSUE TITLE
Looping Error when assigning the data file

### ISSUE THREAD

**Issue by Xeyod** [Zylann/godot_heightmap_plugin#331]
When assigning the data file for the terrain, afterwards it loops this error. 
`"res://addons/zylann.hterrain/hterrain.gd:1177 - Invalid call. Nonexistent function 'update' in base 'Nil'."`

**To Reproduce**
1. Enable addon
2. Assign the data directory
4. See error and lack of terrain

**Expected behavior**
The terrain to appear after assigning the folder

**Screenshots**
Taken When I added the Hterrain Node into the scene
![image](https://user-images.githubusercontent.com/61171174/180326409-824949f1-da85-4f1b-9e74-b4b328af820e.png)

Taken once i assigned the directory
![image](https://user-images.githubusercontent.com/61171174/180326770-86eeca3b-649e-45b3-9857-bd232a10635a.png)

**Environment**
- OS: Windows
- Graphics card: Intel(R) HD Graphics 400 (Don't judge lol)
- Godot version V3.4.4
- Plugin version: Master, 1.6.1 1.6 1.5 (I've tried many)
- Renderer used: GLES3

**Comment by MGilleronFJ** [comment]
Does it still happen if you restart the editor and try again?

**Comment by tinmanjuggernaut** [comment]
Please turn on your console and include all of the errors. Or attach your log file for the session.

**Comment by Xeyod** [comment]
> Does it still happen if you restart the editor and try again?
> 
> Looks like QuadTreeLod just decided it would not instantiate (quite litterally): Some errors occured before you get to assign the data. It mentions that `.new()` is called on a `null` instance here
> 
> https://github.com/Zylann/godot_heightmap_plugin/blob/0eee9691eed7aca2828a37e4f542df05186470ef/addons/zylann.hterrain/native/factory.gd#L32-L36
> 
> 
> Which, if you notice, is complete science fiction. The `if` passes for being not null, but then it complains it can't call `new` on a null instance. That's impossible to fix in GDScript unless the native version of QuadTreeLod is turned off entirely... I have no idea what is even happening here.
> Looks related to what @tinmanjuggernaut added in #281

I’ll give it a try, but I believe it

**Comment by Xeyod** [comment]
I did try to restart the editor and the same thing happens. But I can try again.

**Comment by Xeyod** [comment]
![image](https://user-images.githubusercontent.com/61171174/180519305-22146754-756f-4257-b5e5-e98d4209a75a.jpg)
@tinmanjuggernaut 
Here’s the console once I assigned the directory

> Please turn on your console and include all of the errors. Or attach your log file for the session.

**Comment by Zylann** [comment]
Note, I'm on Windows too and I can't reproduce this. Terrain works just fine.

**Comment by Xeyod** [comment]
Perhaps I broke something in godot?

**Comment by Zylann** [comment]
Is your OS 32 or 64 bits?

**Comment by Xeyod** [comment]
It’s 64

**Comment by Zylann** [comment]
- Godot says there is no library for the target platform when there clearly is, so it is clearly misreporting and the real problem is not even printed
- Godot still returns non-null for a resource that should have failed to load so this cannot be fixed
- I and others can't reproduce this on the same OS and Godot version

At this point my guesses are:
- Yes you broke something somewhere that makes the library unable to load or being detected
- Maybe the library depends on something your computer is a rare one to not have installed, but if that is the case it would be reaaaally nice to get some feedback on what that is. A possible one is the Visual Studio redistribuable (I dunno which one), as I see the library compiles with the `/MD` flag which I think expects the OS to find the `MSVCRT.dll` itself. Using `/MT` instead bundles it inside the library (but makes it larger). But again... would be really nice to confirm that theory with something other than that misleading `does not have library for current platform`.

**Comment by Xeyod** [comment]
So what would your recommended actions be?

**Comment by Zylann** [comment]
One test could be to place `msvcr<version>.dll` next to `hterrain_native.dll` to see if that helps. The CI uses Visual Studio 2022 to build so the matching version has to be used.
Another way to get that library is to use this installer: https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by Xeyod** [comment]
Soooo, I didn’t build godot, I can’t find the directory. The .exe is just on my desktop. Unless I’m not seeing the truth.

**Comment by Zylann** [comment]
The terrain plugin comes with a dll in `addons/zylann.hterrain/native/bin/win64`. This is where the library is.

**Comment by Xeyod** [comment]
Oh okay, thank you, I’ll try it out me I get home.

**Comment by tinmanjuggernaut** [comment]
Is this a mono build or the standard 64—bit certain? I haven't seen those "*daemon running" lines before at the beginning. This still isn't the full log. Go to the log directory and attach the full log file.

%APPDATA%\Godot\app_userdata\[project_name]
https://docs.godotengine.org/en/stable/tutorials/io/data_paths.html

How did you download Zylann's add on? This is saying it can't find or load a dll file. You may have made a mistake in installation.

**Comment by Calinou** [comment]
> I haven't seen those "*daemon running" lines before at the beginning.

These lines are printed by adb, which is called by Godot when an Android export preset is present in the project.

**Comment by Zylann** [comment]
![image](https://user-images.githubusercontent.com/1311555/180614610-cd05d2e6-e773-445c-b183-3ab9862d5dc6.png)

You are running a 32-bit version of Godot. The library is only compiled for 64-bit. Any specific reason you're not using Godot 64 bits if you are on a 64-bit OS?

**Comment by Xeyod** [comment]
Oh, I didn’t realize. I just hit the download button and that’s what I gave me. Should I get the 64 version?

**Comment by Calinou** [comment]
> Should I get the 64 version?

Yes :slightly_smiling_face:

**Comment by Xeyod** [comment]
Gotcha I’ll do that now

**Comment by Xeyod** [comment]
Let’s hope this works, I’ll try it with the 64 bot version of godot and get back to you guys

**Comment by Xeyod** [comment]
Oh yay it works 😊 Thank you to everyone for your help. And @Zylann i can’t wait to finally use your awesome addon.

**Comment by Zylann** [comment]
The latest version now checks architecture so 32-bit Godot should be working, but it won't use native functionality, so 64-bit is still recommended if possible.
