### ISSUE TITLE
Assertion Failed

### ISSUE THREAD

**Issue by Miguelgodot** [Zylann/godot_heightmap_plugin#332]
Hello, I'm new to godot, and I discovered this incredible asset, but when I try the project, I get this error:

Assertion failed.

0-res://godot_heightmap_plugin-85c43173f937b083e216c5f2b911a41e02/addons/zylann.hterrain_data.gd:962 -at function:_load_metadata
1-res://godot_heightmap_plugin-85c43173f937b083e216c5f2b911a41e02/addons/zylann.hterrain_data.gd:1036 - at function:_load_data
2-res://godot_heightmap_plugin-85c43173f937b083e216c5f2b911a41e02/addons/zylann.hterrain_resource_loader.gd:26 -at function:_load

I would really appreciate an answer

**Comment by Calinou** [comment]
Which Godot version are you using? Did you download a 32-bit or 64-bit editor? A 64-bit editor is absolutely required.

**Comment by Miguelgodot** [comment]
I am using version 3.4.4 64x with opgl 3.0 and a gtx 1080

**Comment by Zylann** [comment]
The line of the assertion does not match the repo. It also doesn't match the version downloadable from the asset library. I assume this is the line?
https://github.com/Zylann/godot_heightmap_plugin/blob/0eee9691eed7aca2828a37e4f542df05186470ef/addons/zylann.hterrain/hterrain_data.gd#L954
If yes, it means the plugin was unable to save a file. Means there is something unusual with your setup. How and where did you create your project? How did you install the plugin?

**Comment by Miguelgodot** [comment]
I fixed it, I downloaded the plugin via godot instead of google

Thanks a los

**Comment by Miguelgodot** [comment]
I fixed it, I downloaded the plugin via godot instead of google

Thanks a los
