### ISSUE TITLE
On map import, allow floats for min and max height

### ISSUE THREAD

**Issue by MJacred** [Zylann/godot_heightmap_plugin#340]
**Describe the bug**
My imported terrain (raw file) has a height of 320.574 m. The importer rounds this to 321 m, causing rounding issues on import.

**To Reproduce**
[hmap.raw.zip](https://github.com/Zylann/godot_heightmap_plugin/files/9389066/hmap.raw.zip)
extract raw file (which github does not allow to upload on its own) and import as usual

**Expected behavior**
Correct rounding on import.

**Screenshots**
see https://github.com/Zylann/godot_heightmap_plugin/issues/327#issuecomment-1221531102

**Environment**
- OS: Linux
- Graphics card: Nvidia
- Godot version: 3.3.4
- Plugin version: 1.6.1
- Renderer used: GLES3

**Notes**
`hterrain_data.gd:_import_heightmap()` uses these values for height range in a float context anyway

**Comment by Zylann** [comment]
Added in 778907a8c4b66f513f6a5b0f4f0bf6207f1ef99d, let me know if it works for you

**Comment by MGilleronFJ** [comment]
Can probably be closed then.
About the precision steps you get, I think that's just a limitation in how the plugin stores the heightmap. It uses half-precision floats. See the available intervals within height ranges here: https://en.wikipedia.org/wiki/Half-precision_floating-point_format#Precision_limitations
In the future I think I'll change the plugin to use RGB8 (1 more byte of precision) which would be limited to about -16..16 Km heights and allow linear intervals of about 1/100 per meter at any height.

**Comment by MJacred** [comment]
As this issue is about controlling input, yes, it can be closed

The import process looks correct (checked for raw files), so it's not in that part… 
The storing sounds plausible. Absolute same visual result when `make_heightmap_mesh` is executed

For reference, the round hill's max position is at 287.279 m

And the bumpier terrain shown here https://github.com/Zylann/godot_heightmap_plugin/issues/327#issuecomment-1222378178 ends at height 162.134 m

**Comment by MJacred** [comment]
Wait, don't you mean FORMAT_RF instead of FORMAT_RGB8?

**Comment by Zylann** [comment]
I meant RGB8, which is 3 bytes. RF is 4 bytes and looses precision the higher you go, so I think RGB8 is more efficient.

**Comment by MJacred** [comment]
I see… splitting float in RGB8 for a 24-bit float sounds interesting
