### ISSUE TITLE
Raise brush has steps

### ISSUE THREAD

**Issue by Norodix** [Zylann/godot_heightmap_plugin#345]
**Describe the bug**

When applying the raise brush to a terrain it creates weird step patterns.

I first noticed it when the terrain became unexpectedly bumpy after editing, but the issue is most visible when using a small opacity brush on the same very small area for a few seconds. (see screenshot).

I suspected the reason is the small resolution brush but it seems that is not the case. I edited the raise shader to not use the bursh image but a gradient coded in the shader and I still run into the same issue. 

Another weird artifact that I noticed is when trying to mess with this raise shader is that I cannot seem to be able to adjust the height by very small amounts. When I tried to add the following code for debug purposes, the height did not change at all, until I raised the `brush_value` to 0.125.

```
void fragment() {
	float brush_value = u_factor * u_opacity * texture(TEXTURE, UV).r;
	brush_value = 0.1;
	float src_h = texture(u_src_texture, get_src_uv(SCREEN_UV)).r;
	float h = src_h + brush_value;
	COLOR = vec4(h, 0.0, 0.0, 1.0);
}
```
I suspect this is related. 

**To Reproduce**
1. Create a Hterrain
2. Grab the raise brush
3. set the size to about 200 and the opacity to 4
4. Try to slowly draw on the terrain

**Expected behavior**
The plugin produces a smooth surface without steps.

**Screenshots**
![image](https://user-images.githubusercontent.com/36245389/195995572-7b999298-755a-45aa-8124-6f19be27a008.png)
The hills were made with 20, 4 and 2 as opacity setting (left to right).

**Environment**
System:
  Host: pop-os Kernel: 5.19.0-76051900-generic x86_64 bits: 64
    Desktop: GNOME 42.3.1 Distro: Pop!_OS 22.04 LTS

Godot v3.5.stable
Plugin version: 1.6.1
GLES3

**Comment by Zylann** [comment]
This is likely to be expected. Terrain heights currently use half-precision floats (16-bit), so while it is enough to represent decent hills, doing a lot of very small edits is prone to producing artifacts. Because small values + done many times makes precision errors accumulate a lot more. There is no workaround for this currently, maybe apart from changing heigntmap format, but that's currently not supported.

**Comment by Norodix** [comment]
I'm not sure that is the root cause of the issue. It might be but when I do the same operation on a sloped surface the steps dont appear at constant heights, they only appear radially. 
So I think the intermediate values can be stored in this format.
What do you think?
![image](https://user-images.githubusercontent.com/36245389/196001568-d2f4ee9a-1e20-49bc-98a8-4fc5332b6b7c.png)

**Comment by Zylann** [comment]
You already tested using a brush with full precision, so there aren't many possibilities left.

**Comment by Norodix** [comment]
I dont see a reason why the height parameter's precision would be affected by the size of the brush.

Is there a reason the plugin is using half precision floats? Can this be changed relatively easily in the code to test if the problem is solved by 32bit floats?

**Comment by Zylann** [comment]
> I dont see a reason why the height parameter's precision would be affected by the size of the brush.

The height of the ground you paint on has an effect (but not on the size of the brush (?)) because the higher a height is, the lower precision becomes. It's like floating point precision loss when getting far from the origin, same deal here.

> Is there a reason the plugin is using half precision floats? Can this be changed relatively easily in the code to test if the problem is solved by 32bit floats?

It was good enough for a long time, and it uses twice as less memory than full floats. It is really all you need in a large variety of cases. This specific painting case doesnt grant doubling memory usage in-game, though indeed it is annoying.
I suppose it is relatively easy to replace all occurrences of RH in the plugin to RF, but 1) it will double memory usage in all the cases that were doing fine with RH, 2) it will break compatibility, 3) gives no choice.
The format I considered using is actually not floats, but RGB8. 24-bit fixed-point is more precise, has the same precision at all heights, and supports higher heights, although it needs conversion when accessed. Besides, if necessary, in the future it could be changed to RGBA8 where A stores additional information in a single fetch (but that's just an idea).
Eventually conversion choices could be given on top of that.

**Comment by Norodix** [comment]
I tried changing the image format to Image.RF (see image format). I might have missed something so take this with a grain of salt but look at the screenshot.

I marked 2 points. If the red point was not possible to represent due to floating point precision issues, how could the green point be represented? Why would it produce nice slopes along the steps?

If I understand correctly the brush is applied by using a background sprite, adding the brush sprite on top of it and rendering it to a viewport. It feels a bit like the brush sprite has a different format with only 8bit color, but I cannot find where the sprites texture's format is set. (or if can be specified at all).

![image](https://user-images.githubusercontent.com/36245389/196019615-d7de9f7c-ba36-4297-b111-677e608f6b39.png)

**Comment by Zylann** [comment]
Unfortunately viewports use half-precision floats too (another reason why RGB8 could have been better), so actually it might not be possible to do right now.

**Comment by Calinou** [comment]
Could dithering be added to make banding less visible? This would cause visible bumps to appear in terrain though.

> The plugin uses viewports to make brushes fast. It isn't possible to increase them to full floats, so actually it might not be possible to do right now.

[Viewports can use 32-bit precision in 3.x](https://github.com/godotengine/godot/pull/51708), but not in 4.0 yet.

**Comment by Zylann** [comment]
Dithering helps when you render something *once* at low precision. Here it's an accumulation, so with dithering it would probably result in noise.

> https://github.com/godotengine/godot/pull/51708

Ah, so maybe this is the last bit to change in addition to using RF for textures.

**Comment by Norodix** [comment]
This absolutely solved the problem in my case!
Bumps on the right were made before the change, the big one on the left was after. (I had to reload the plugin)

![image](https://user-images.githubusercontent.com/36245389/196053998-c813da82-bb69-4379-85a4-69f0f2d162f2.png)

Maybe doing the edits with full precision floats and storing the result with half precision as currently done could be implemented? The terrain did not feel jagged, only the edits so maybe this could be a useful change until the bigger work is started with the more detailed solution you mentioned (RGBA8, configurable precision, etc).

**Comment by Norodix** [comment]
Actually the original problem I had was smoothing didn't seem to work very well. That is how I found this issue and I was convinced it is related. I reported this because this was more obvious and reproducible. 

![image](https://user-images.githubusercontent.com/36245389/196276851-145fd57d-80ba-4797-8570-15ca00941f86.png)

On this image you can see that the peak on the right (with the brush on it) was smoothed with full float precision. It is nice and smooth. In the foreground you can see the peak that was smoothed with half precision has visible artifacts.

**Comment by Zylann** [comment]
It's probably a matter of degree, I havent seen these artifacts before. Maybe they tend to also occur more with low opacities or high heights.

**Comment by Zylann** [comment]
> Do you think it is worth trying to move the edits to 32 bit floats for a less intrusive fix

Unfortunately I think doing that is not possible at the moment, each edit gets stored back into the heightmap, they dont stay in the viewport. The viewport is only the size of  the brush and can move arbitrarily.

**Comment by Norodix** [comment]
As far as I can tell, this has been done in v4, so it can be closed.
Thanks for the great addon again!
