### ISSUE TITLE
EXR heightmaps not importing correctly

### ISSUE THREAD

**Issue by Kaveesha4478** [Zylann/godot_heightmap_plugin#347]
**Describe the bug**
after importing .exr heightmaps terrain freezes, terrain is flat as before, brushes stop working

**To Reproduce**
1. Open import maps menu
2. Import .exr heightmap
3. After exporting try to use brushes
4. Terrain is flat and doesn't get affected by brushes

Heightmap : [height.exr](https://mega.nz/file/eNp3hB5C#RRqDl_woXtXAEEmj8jT4A-KzwZbTky0f13-rsKBcCIk)

**Environment**
- OS: Linux 64-bit (ubuntu)
- Graphics card :GeForce GT 240
- Godot version : 3.4.4 , 3.5.1
- Plugin version : 1.6.1
- Renderer used: GLES3

**Comment by Zylann** [comment]
FYI, your EXR is using 32-bit RGBA floats, while this plugin expects 16-bit greyscale floats (single channel).

I created a new scene, added a terrain in it, and selected a data folder.
Then I tried importing your terrain, but apart from fitting for the size of your map (2049 in this case) nothing special happened. And I was able to sculpt the terrain afterwards.

In fact, it looks like your EXR really is completely flat. I had a look at it in RenderDoc, and all pixels have zero values.

![image](https://user-images.githubusercontent.com/1311555/197361756-838487df-1ae5-40f3-8069-2e499cbe887d.png)

**Comment by Kaveesha4478** [comment]
Thank you very much for quick reply.
After scaling Y value of terrain to about 1000 it shows the heights correctly.Brushes didn't work at first but after saving the scene and restarting godot they work as expected.I think it's my old hardware.
Thank you very much for your help.

**Comment by Zylann** [comment]
> After scaling Y value of terrain to about 1000 it shows the heights correctly

You shouldn't need to do this though, that stuff should be investigated eventually
