### ISSUE TITLE
Importer not loading textures in array mode

### ISSUE THREAD

**Issue by pietru2004** [Zylann/godot_heightmap_plugin#349]
**Describe the bug**
When I try to import new-additional texture to texture array importer does not load already present textures and it does not save import directory.

**Screenshots**
![obraz](https://user-images.githubusercontent.com/51274570/200123196-e7a22e8a-91eb-46f4-97ad-9f115a3e4a70.png)
Also I have defined 4 textures and am using MultiSplat16Lite cause else terrain looks like 1 big mirror

**Comment by MGilleronFJ** [comment]
What are all the steps you are taking to reproduce this issue?

Keep in mind the *importer* will only have pre-filled textures in it if you already used the *importer* before.
Because the way it finds the previous textures is by checking the presence of files produced by a former import. So if you setup textures directly without import, it will indeed not show you anything because your initial textures were not *imported* (and might not even have been texture arrays, I have no way to tell without detailed steps).

> am using MultiSplat16Lite cause else terrain looks like 1 big mirror

That could be a separate issue, but basically the other shader requires normalmaps and should not look like a mirror... unless you *did not use the importer*. Because the shader packs *roughness* into normalmaps's alpha channel. If you don't use the importer and give it a non-packed normalmap directly, it will indeed look like a mirror.

**Comment by pietru2004** [comment]
After restarting godot I don't see sruf loaded into TextureArrays importer - it shows up when using standard 4 texture mode

**Comment by MGilleronFJ** [comment]
Please describe precisely all the steps you are doing.

**Comment by pietru2004** [comment]
1. Load textures for the first time in Array Mode
2. Click Import with having directory set
3. Repeat Steps 1-2 for second terrain or copy terrain folder to make second terrain
4. Restart Godot
5. It does not load textures into import list.

Also version 1.5.2

**Comment by Zylann** [comment]
It lacks details, but I did it and could not reproduce the problem. When I restart Godot and click `Import...` again to import more textures, I see the current textures already there. Using the latest version from Github (1.6.2).

What I did exactly:
1) Created a new terrain, chose data folder to be `terrain1/` in the inspector.
2) Saved the scene.
3) I clicked this: 
![image](https://user-images.githubusercontent.com/1311555/200650658-164cca06-d287-4e6d-90f0-bb4012a27348.png)
4) In the dialog that opens, I changed `import mode` to `TextureArrays`
5) Added a new slot, and loaded an albedo texture
6) Clicked "Import to textureSet". After some progress bar, "Import complete" popup shows up, I click Ok, and close the dialog. This also makes the first texture appear in the terrain.
7) I repeated steps 1 to 6 with another scene.
8) Closed Godot
9) Reopened Godot, opened the first scene I made: the terrain still had textures. I clicked the same `Import...` button at the bottom, and the dialog still had the textures in it.

**Comment by pietru2004** [comment]
hm seams I have older version (1.5.2 so it might have been fixed in the past)

I did basicaly

1. create terrain 
2. import textures
3. duplicate hterrain node
4. duplicate terrain data folder (import directory is separate folder)
5. set second terrain path to the duplicated node
6. look at import once - in theory should have textures
7. reopen godot - should have no textures in when switching nodes

**Comment by Zylann** [comment]
I did the same things you did I think, and still no issue.

**Comment by pietru2004** [comment]
well I will try update plugin - mayby it is something old that was fixed some time ago

**Comment by pietru2004** [comment]
hm...
![obraz](https://user-images.githubusercontent.com/51274570/200689715-b9598110-5a91-4fb4-b7d8-c22badb5a960.png)
store says 1.6.1
godot says I have 1.5.2

**Comment by pietru2004** [comment]
271 conflict files.. why I can't just press override... 
well
![obraz](https://user-images.githubusercontent.com/51274570/200690415-28c1d935-1e98-4944-b4c5-beac34b5b92d.png)


It works now, also when I click from one HTerrain node to second it does not load stuf - probably refreshing issue
![obraz](https://user-images.githubusercontent.com/51274570/200690761-82fb278d-a741-4dd3-a04c-6d2fb5242d7a.png)

**Comment by Zylann** [comment]
> store says 1.6.1 godot says I have 1.5.2

Well when I download from the assetlib (via web browser) and look into `plugin.cfg` it says 1.6.1. 

> 271 conflict files.. why I can't just press override...

Overwriting should be fine. Usually to update a plugin, I recommend to turn it off, close Godot, delete the old plugin, add the new plugin manually, open Godot and enable it. Yes, it's tedious, and Godot's UI for this isn't acknowledging this use case, or assumes that leaking any potentially moved/renamed files is fine...

> when I click from one HTerrain node to second it does not load stuf - probably refreshing issue

There is an error printed that could relate to this. Looks like another issue.

**Comment by pietru2004** [comment]
> Well when I download from the assetlib (via web browser) and look into plugin.cfg it says 1.6.1.
I might have forgot to update plugin for like year

> Overwriting should be fine
IK It is just annoying there is no btn by default for this

**Comment by Zylann** [comment]
I fixed the texture list becoming empty. It happens because the two terrains share the same TextureSet resource and the editor was assuming it was always different.
