### ISSUE TITLE
Custom Generation Methods

### ISSUE THREAD

**Issue by NiklasTaube** [Zylann/godot_heightmap_plugin#354]
Hello,
I want to generate Terrain with different algorithms, e.g. Midpoint Displacement, Value Noise, .... However, I have no idea how I can transform the grids generated from the algorithms into actual 3D Terrain. Since this plugin is using the same kind of grids (2D arrays), I thought about finding the function in the code of the plugin that takes the grid as an input and starts processing it into a terrain, but i haven't found it after 3 days of searching through the plugin codebase.

**Comment by MGilleronFJ** [comment]
To generate a terrain in general you only have to generate images. Once you have images you can set them up when creating the terrain node. How you generate such images is up to you. It can be with the `Image` API in GDScript, or using viewports and shaders. See https://hterrain-plugin.readthedocs.io/en/latest/#procedural-generation

If your specific problem is to apply something on top of the generator provided in the editor, this generator is currently not available outside the editor, there is no API for it. But all it does is using a viewport and shaders to generate images, which then are applied on the terrain. You can find its code here: https://github.com/Zylann/godot_heightmap_plugin/tree/master/addons/zylann.hterrain/tools/generator
