### ISSUE TITLE
Do I need to give credit if I use this plugin?

### ISSUE THREAD

**Issue by ElsAr4e** [Zylann/godot_heightmap_plugin#357]
There has been a similar question but it was mentioned that using this plugin involves giving credit: https://github.com/Zylann/godot_heightmap_plugin/issues/256

> with credit of course.

If I use this plugin in commercial games do I have to give credits? Or is this just a voluntary choice?

**Comment by Zylann** [comment]
This plugin is licensed under MIT, which is the same license as Godot: https://godotengine.org/license/
Therefore you must at least have a copy of this plugin's license in a place of your game accessible to players.

**Comment by ElsAr4e** [comment]
Thank you for clarifying my question!
