### ISSUE TITLE
No GDNative Library

### ISSUE THREAD

**Issue by Assassin121YT** [Zylann/godot_heightmap_plugin#370]
**Describe the bug**
There is no GDNative Library for Win64 under native folder

**To Reproduce**
1. Import the plugin to Godot
2. I go to project > project settings > plugins then I find no plugin to enable
3. I notice the output panel saying "does not have a library for the current platform"
4. I check the native file and I only find 3 folders each for linux, macOS and win64, all empty
Linking a reproduction project may help.
If you see any errors in the console, that may also help.

**Expected behavior**
To have the GDNative Library

**Screenshots**
![image](https://github.com/Zylann/godot_heightmap_plugin/assets/133807703/a780ce51-e41a-4c49-8916-06a53dcf46ed)

**Environment**
- OS: Windows 10 Home
- Graphics card (you can find out in Godot's console log): NVIDIA GeForce MX450/PCIe/SSE2
- Godot version [e.g. 3.2.1]: 3.5.1
- Plugin version (or commit hash if you got it from Github directly): #
- Renderer used: note that GLES2 is not supported.: GLES3

**Comment by MJacred** [comment]
That's just a bug in Godot, see here: https://github.com/Zylann/godot_heightmap_plugin/issues/156#issuecomment-616880175

The Godot Editor lies to you, please check in your file browser, the file should be there:

![image](https://github.com/Zylann/godot_heightmap_plugin/assets/6639237/dc2d4806-4234-4e27-805c-d9b75b638c78)

**Comment by Assassin121YT** [comment]
What do I do to run the plugin them?

**Comment by Assassin121YT** [comment]
What do I do to load the plugin?

**Comment by MJacred** [comment]
See documentation ; )

https://hterrain-plugin.readthedocs.io/en/latest/#gdnative


Am 19. Mai 2023 12:46:15 UTC schrieb Assassin121YT ***@***.***>:

**Comment by Assassin121YT** [comment]
It is ok now
