### ISSUE TITLE
Camera3D in a scene with HTerrain node instantiated as a child-scene shows black screem

### ISSUE THREAD

**Issue by Assassin121YT** [Zylann/godot_heightmap_plugin#373]
**Describe the bug**
So I have a scene with my world, this world contains an HTerrain node, a few character bodies, some other Node3Ds which contain other objects (to make a castle) and the camera3d, if it is related I use Classic4lite shader for my HTerrain Node

**To Reproduce**
1. make your HTerrain node in a seperate scene
2. complete the brushes and stuff
3. instantiate that scene into the main scene
4. Add camera to the main scene
5. Run the main scene
6. See a black scene

**Expected behavior**
I expected to see through the camera

**Screenshots**
![image](https://github.com/Zylann/godot_heightmap_plugin/assets/133807703/96b847c2-2db8-4097-907b-7f07474c4594)

**Environment**
- OS: Windows 10 Home
- Graphics Card: Nvidia GeForce MX450
- Godot version: 4.0.3
- Plugin version: The latest one for godot 4
- Renderer used: Forward+

**Comment by Zylann** [comment]
If you can't even see the environment, I suspect this is a Godot bug or a problem of setup... there is no way this plugin can completely obliterate the whole rendering.

**Comment by Assassin121YT** [comment]
My apologies for taking so long, anyway, here is the project where the problem occurs, although I can't provide a minimal repro project, this is what I can give (full project)

**Comment by Assassin121YT** [comment]
My apologies again, while making the minimal repro project, I realised the problem existed because the environment of the camera was set to default.env.tres, showing nothing
