### ISSUE TITLE
godot4 branch: Each Open of import file chooser dialog connects to signal 'file_selected'

### ISSUE THREAD

**Issue by MJacred** [Zylann/godot_heightmap_plugin#374]
**Describe the bug**
Each Open of import file chooser dialog connects to signal 'file_selected'

```sh
Signal 'file_selected' is already connected to given callable 'VBoxContainer(inspector.gd)::_on_file_selected' in that object.
```

Import still works.

**To Reproduce**
1. open import dialog: Terrain > Import Maps…
2. open file chooser for heightmap
3. close file chooser dialog
4. repeat step 2. -> triggers error message

**Environment**
- Godot version: 4.0.3
- Plugin version: baeaba83345e1a5017587dd235749df5a528ef66

**Comment by Zylann** [comment]
That signal is supposed to be disconnected when the dialog's visibility becomes `false`: https://github.com/Zylann/godot_heightmap_plugin/blob/5273707cab9d179dcae97000c59cab6f6645744e/addons/zylann.hterrain/tools/inspector/inspector.gd#L445

The signal is emitted when the dialog opens, but... not when it is closed :|

**Comment by Zylann** [comment]
Try with 778889bb7157f3a97ed644634dce9996d1fa144f

**Comment by MJacred** [comment]
> Try with [778889b](https://github.com/Zylann/godot_heightmap_plugin/commit/778889bb7157f3a97ed644634dce9996d1fa144f)

Fixed  :+1: 
Error message does not appear, and import process stays unaffected
