### ISSUE TITLE
Exported game uses not all textures and detail layers only in Debug Builds

### ISSUE THREAD

**Issue by CentiGames** [Zylann/godot_heightmap_plugin#380]
**Describe the bug**
I use the Heightmap terrain plugin, and when trying to export the game using the "Export with Debug" option everything works. However, if I don't export with debug, the Height map terrain has only 1 texture (or at least the other textures are not very visible), and no detail layers are being shown.

**To Reproduce**
1. Create an HTerrain node
2. Select a data directory, set Shader Type to MultiSplat16, 
3. (I also saved the Texture Set as a resource, not sure if that's necessary though)
4. Import at least 2 textures (I imported using ImportMode TextureArrays)
5. Add a DetailLayer (optional)
6. Paint the two textures on the terrain and add some details to the DetailLayer
7. Project > Export... > Export Project > (Make sure "Export with Debug" is NOT checked) Save build somewhere
8. Start the Release build

**Minimal Reproduction Project**
I made a minimal reproduction project (shown in the screenshots below):
[HTerrainNonDebugExport.zip](https://github.com/Zylann/godot_heightmap_plugin/files/12113956/HTerrainNonDebugExport.zip)
I didn't include the build to save some file size, let me know in case you should need it, but I think you should be (hopefully?) able to reproduce the issue when exporting yourself.

There are no errors in the console when running the game, however, when exporting I get `Cannot erase nonexistent section "params"`, but I get that no matter if I export with or without debug.

As mentioned, I used MultiSplat16 for the project. I also tested using Classic4Lite, and the textures seem to work there, but I still did not get the DetailLayer. (see screenshots below also for those)

**Expected behavior**
I expect the exported build without debug (release) to look the same as the terrain looks in the Editor/debug builds.

**Screenshots**
MultiSplat16
| Running via Editor & Exported with Debug | Exported without Debug (Release) |
|--------|--------|
| ![image](https://github.com/Zylann/godot_heightmap_plugin/assets/105640257/f16f440d-88e0-4670-8925-5b652259d443) |  ![image](https://github.com/Zylann/godot_heightmap_plugin/assets/105640257/7410ef36-8a46-41a6-8463-12e0843b4e51)|

Classic4Lite
| Running via Editor & Exported with Debug | Exported without Debug (Release) |
|--------|--------|
| ![image](https://github.com/Zylann/godot_heightmap_plugin/assets/105640257/162c6ab9-0896-46a5-b430-788f842459a6) | ![image](https://github.com/Zylann/godot_heightmap_plugin/assets/105640257/98a31cf5-f0ab-4ebe-bcc7-1d80175bff45)|

**Environment**
- OS: Windows 10
- Graphics card: RTX 3070
- Godot version: 4.1.1
- Plugin version: Latest commit on the repository https://github.com/Zylann/godot_heightmap_plugin/commit/7c73ffbbb6a10895e2e0330ea328cec698536de7
- Renderer used: Forward+

Please let me know if you need further information regarding the issue.

**Comment by Zylann** [comment]
There is only one known issue which can cause the played/exported game to look different, is the fact Godot does not reimport textures generated by the plugin, and has no way to tell Godot to re-import them. So the only way is to tab in/out before playing or exporting. I tested an export myself from scratch and could not get any issue.

Now, if differences still occur in your project, and on top of that, are different between Debug and Release exports, then something is really suspicious about Godot... because the plugin has no special code that runs in debug mode or not debug mode... there is nothing affecting the way it loads or run the terrain. 
So I tend to suspect there is a lurking Godot bug in this...

**Comment by Zylann** [comment]
It appears the detail map didn't load at all in the non-debug build. But still no idea why. Having to debug this by dumping files and rebuilding 😭

**Comment by Zylann** [comment]
I replaced the logger with a file dumping logger.

I placed a print at the beginning at this function:
https://github.com/Zylann/godot_heightmap_plugin/blob/7c73ffbbb6a10895e2e0330ea328cec698536de7/addons/zylann.hterrain/hterrain_data.gd#L1048
I noticed that despite terrain data loading (except the detail map), this line never printed in non-debug.

So I started placing logs around this location:
https://github.com/Zylann/godot_heightmap_plugin/blob/7c73ffbbb6a10895e2e0330ea328cec698536de7/addons/zylann.hterrain/hterrain_data.gd#L1013
And magically, grass started appearing again. Like, what the actual fuck. I'm just logging things :|

**Comment by Zylann** [comment]
Got this one to reproduce consistently, I think:
![image](https://github.com/Zylann/godot_heightmap_plugin/assets/1311555/c3e4742b-2f66-400a-ab4a-3995c4f94956)

I dared printing `json.data` then, and it turns out it's `null`. That's not normal of course because it works perfectly in editor AND debug exports... so why is it null OO

**Comment by Zylann** [comment]
Turns out `assert` has to be hunted down for important code because they are stripped INCLUDING THEIR ARGUMENTS in release builds...
https://github.com/godotengine/godot-proposals/issues/502

**Comment by Zylann** [comment]
Patched in 94f4c00f37a1ed4fe4d23067bcb584a57d294757
You can download the fix from the master branch, the asset library version will get updated some time later

**Comment by CentiGames** [comment]
Everything works now! THANK YOU SO MUCH! I am beyond grateful and impressed with how quickly you managed to hunt this nasty bug down. Thanks a lot! 😄
