### ISSUE TITLE
Jolt physics support

### ISSUE THREAD

**Issue by dnasnipp** [Zylann/godot_heightmap_plugin#381]
**Is your feature request related to a problem? Please describe.**
Currently it doesnt works with custom Godot Jolt Physics
https://github.com/godot-jolt/godot-jolt

**Comment by Calinou** [comment]
- See https://github.com/outobugi/Terrain3D/discussions/152 for why it doesn't work.

**Comment by Zylann** [comment]
AFAIK this isn't something to solve on the side of the terrain plugin.

**Comment by dnasnipp** [comment]
Okay, thanks you for the information
