### ISSUE TITLE
NormalMap

### ISSUE THREAD

**Issue by DxUr** [Zylann/godot_heightmap_plugin#383]
Normal Map does not work

**Comment by Zylann** [comment]
Please fill the issue template. 

Which renderer did you use? Which version of the plugin? Which version of Godot? Which shader type? Which steps did you follow?

I used normalmaps in one of my test scenes and they work.
![image](https://github.com/Zylann/godot_heightmap_plugin/assets/1311555/ff31abc4-5d23-4e3f-a0c4-c10b1f878119)

**Comment by DxUr** [comment]
Thanks I was using Classic4Lite shader, I switch to Classic4.
