### ISSUE TITLE
Low polygons

### ISSUE THREAD

**Issue by DxUr** [Zylann/godot_heightmap_plugin#384]
When scaling up, the map polygons do not increase, so terrain quality tends to be lower and lower.

**To Reproduce**
1. Scale up the terrain

**Expected behavior**
  generate more polygons when scaling up terrain
and if there is a way to add more polygons without scaling the map or make it more smaller.

**Environment**
- OS: Windows x64
- Graphics card AMD Radeon(TM) Graphics
- Godot version 4.1.1
- Plugin version 1.7.1
- Renderer used: Forward+.

**Comment by Zylann** [comment]
> When scaling up, the map polygons do not increase, so terrain quality tends to be lower and lower.

That's what scaling does. Scaling your terrain will not magically increase its resolution. To increase resolution, you have to use the resizing tool in the toolbar `Terrain` -> `Resize`

**Comment by DxUr** [comment]
Thanks
