### ISSUE TITLE
Error when trying to delete a TextureSet

### ISSUE THREAD

**Issue by ThatCoolCoder** [Zylann/godot_heightmap_plugin#385]
**Describe the bug**
When I open the TextureSet editor and click on the button to remove a texture, nothing happens and the following error appears in the console: `res://addons/zylann.hterrain/hterrain_texture_set.gd:217 - Invalid call. Nonexistent function 'remove' in base 'Array'.`

**To Reproduce**
1. Add a new hterrain node to the tree
2. Click the edit button in the textures menu in the bottom bar
3. Click the plus to add a texture, then try clicking the minus to remove it.

**Environment**
- OS: Manjaro
- Graphics card: AMD RX 6600
- Godot version: 4.1 stable mono
- Plugin version: 1.7.1
- Renderer used: forward+

**Workaround**
Fortunately it's not too hard to remove it manually by manually editing the scene file

**Comment by Zylann** [comment]
Looks like `remove` was renamed `remove_at`, https://docs.godotengine.org/en/stable/classes/class_array.html#class-array-method-remove-at
probably didn't see it when porting to Godot 4

**Comment by Zylann** [comment]
Should be fixed in 5d447445c21b1afe7f51b7987485c54854554af0
