### ISSUE TITLE
Is there a way to change the color of Low_Poly_Shader in a similar fashion to Classic4Lite?

### ISSUE THREAD

**Issue by Pugulishus** [Zylann/godot_heightmap_plugin#392]
Using the Godot Documentation on the heightmap plugin, I couldn't find a way to apply colors to Low Poly Shader on generation, not using the paintbrush, (Basically the "Scripting/ Procedural Generation" code from the docs, except with low poly and colors instead of Classic4Lite and textures)

Is there something obvious I'm missing, or am I best off making my own shader? And if I should just make my own shader to apply colors, how would I go about applying a SHADER_CUSTOM through code? I know you have to use:
```
terrain.set_shader_type(HTerrain.SHADER_CUSTOM)
```
But I believe you also have to specify a file with another line correct? What would that look like?

Sorry if my questions are a bit stupid, my coding knowledge boils down to google searches

**Comment by Zylann** [comment]
> But I believe you also have to specify a file with another line correct? What would that look like?

The other line would be:

```gdscript
terrain.set_custom_shader(shader)
```

> Using the Godot Documentation on the heightmap plugin, I couldn't find a way to apply colors to Low Poly Shader on generation, not using the paintbrush, (Basically the "Scripting/ Procedural Generation" code from the docs, except with low poly and colors instead of Classic4Lite and textures)

This one shows it with the colormap: https://hterrain-plugin.readthedocs.io/en/latest/#modifying-terrain-from-script
With colors, the shader you use makes no difference. You would need the same things with a custom shader.
The code is just a little outdated (it uses Godot 3 syntax but it's pretty much the same if you remove the `lock`/`unlock` and replace `onready` with `@onready`.
