### ISSUE TITLE
Graphics Glitch when using MultiSplat16 mode (especially with Screen Space Reflection)

### ISSUE THREAD

**Issue by TheConceptBoy** [Zylann/godot_heightmap_plugin#396]
Yesterday I've suddenly started experiencing this graphical glitch if I use MultSplat16. 

![image](https://github.com/Zylann/godot_heightmap_plugin/assets/52581279/37e9c18d-fd8c-40eb-bf0d-6e0081a4f898)

This is with Reflections disabled: 
![image](https://github.com/Zylann/godot_heightmap_plugin/assets/52581279/904cb330-e518-4b96-94bb-dbcea1f0b954)

There is still a black blotch under a character that seems to go away when I paint over it using texture painting. However it's not permanent and the glitch may come back when I run the game / save the scene / close and re-open it.  
https://youtu.be/CPCOkFTNVCo

**Comment by Zylann** [comment]
Same as https://github.com/Zylann/godot_heightmap_plugin/issues/149
We haven't found why that happens unfortunately... we suspect a bug in Godot or drivers or graphics cards drivers just "noping" when there are more han a certain number of textures in a shader maybe.

**Comment by Calinou** [comment]
What graphics card model do you have? Do you have MSAA enabled?

**Comment by TheConceptBoy** [comment]
This is Godot 3.5.2, Windows 10

![image](https://github.com/Zylann/godot_heightmap_plugin/assets/52581279/bb0aeab8-576e-41af-b9dd-35cbee192f11)
![image](https://github.com/Zylann/godot_heightmap_plugin/assets/52581279/d702bafe-eeba-4214-b1f8-f706db19dd6c)
![image](https://github.com/Zylann/godot_heightmap_plugin/assets/52581279/4bc18463-a7d4-453c-b2d4-9970101512a2)

**Comment by Zylann** [comment]
Maybe you can try in Godot 4, because it looks like this bug has only been reported in Godot 3 so far.

**Comment by TheConceptBoy** [comment]
> Maybe you can try in Godot 4, because it looks like this bug has only been reported in Godot 3 so far.

Is this going to be a common trend? Godot 3 is listed for LTS (Long Term Support) but if the solution is to just "move on to Godot 4" then what's the point?

**Comment by TheConceptBoy** [comment]
There are a number of projects I've started in Godot 3 that really don't need to be ported to 4 because they're quite simple in nature and won't really benefit from 4's features. It's more of an option than a requirement.

Something I've learned from my time with Unreal. Don't jump on new fangled engine unless absolutely necessary. Any new projects I have started with Godot 4 and so far enjoying it's bounty of features. But does every project need to be ported?

**Comment by Zylann** [comment]
I'm only suggesting that because I don't even know if this bug also happens in 4 or if it's specific to 3. Either way, if something is broken in Godot's renderer, there is little the plugin can do.

**Comment by TheConceptBoy** [comment]
> I'm only suggesting that because I don't even know if this bug also happens in 4 or if it's specific to 3. Either way, if something is broken in Godot's renderer, there is little the plugin can do, it would require someone more involved in the renderer itself to have a look at why that happens.

Got it. Will keep that in mind

**Comment by TheConceptBoy** [comment]
I suppose we can close this? Since it's not plugin dependent?

**Comment by Zylann** [comment]
I will close it but reference it in https://github.com/Zylann/godot_heightmap_plugin/issues/149 so we can keep track of it
