### ISSUE TITLE
Slowness issue when using instance mesh in detail layer

### ISSUE THREAD

**Issue by bakase** [Zylann/godot_heightmap_plugin#399]
This was written with Google Translator.
.
When registering an instance mesh in the detail layer, the editor itself becomes very slow when registering an object with a large number of polygons. ( 100 - 1000 )
(It seems to slow down in proportion to the number of polygons)

This applies even if you haven't placed anything in the world yet.
  Just registering an instance mesh becomes slower.

Is it a hterrain problem or a godot problem?
.
godot 4.1.1 hterrain 1.7.2 gtx1070

**Comment by Zylann** [comment]
Detail layers are meant for *small* meshes like grass. Therefore, the way they are implemented is based on that assumption. It uses a single fully-covered multimesh which is re-used in chunks around the viewer, and then vertices are culled in the vertex shader. So of course if your meshes are too big, the cost of processing them all will exceed the time gained by culling them. In this case I suggest you use something else to instance these meshes.

**Comment by bakase** [comment]
understand.
.
I now understand what happened when I replaced the custom shader with an unrelated one. (Objects that cover the entire world)
The entire mesh was created in advance and only the visible parts were modified.
(Based on information from related texture data)

.Thanks for the detailed explanation of how it works.

After moving to .godot, I was confused because there was no terrain editor, but thanks to hterrain, I am using it well.

.There is another problem, but I will open that in another thread.
.thank you.
