### ISSUE TITLE
How can I get rid of the 'metallic glow'? 

### ISSUE THREAD

**Issue by NoTitleGamesOfficial** [Zylann/godot_heightmap_plugin#404]
my terrain looks like this:

![Bildschirmfoto von 2023-10-15 16-59-09](https://github.com/Zylann/godot_heightmap_plugin/assets/105103092/2f1eed5a-f5c2-4650-9272-34999ec6bc57)

I would like to disable the 'metallic glow' (I'm not sure what its called exactly) like I can do by setting the 'metallic' value on a spatial material to 0, as I did with this cube:
![Bildschirmfoto von 2023-10-15 16-59-34](https://github.com/Zylann/godot_heightmap_plugin/assets/105103092/41c50ff4-d1c6-40fd-8738-e24a79be068a)
![Bildschirmfoto von 2023-10-15 16-59-41](https://github.com/Zylann/godot_heightmap_plugin/assets/105103092/c14b9efd-e55e-44c2-b1ed-2ecac75e72d7)

I hope you know what I mean. Sorry english isn't my native language so its a bit hard for me to describe it :)

**Comment by Zylann** [comment]
The shader in this plugin does not assign metallic... not sure why you get this difference. I assumed metallic defaulted to 0 in this case.
Which shader are you using?

If you want to choose metallic, you have to edit the end of the shader you are using. But look:

![image](https://github.com/Zylann/godot_heightmap_plugin/assets/1311555/443f88ee-740f-4f95-9082-fb2b513efbe3)

If I set `METALLIC` to 0, the result is the same:
![image](https://github.com/Zylann/godot_heightmap_plugin/assets/1311555/edffd554-b35d-42fd-91bb-ec661194b369)

If I set it to 1:
![image](https://github.com/Zylann/godot_heightmap_plugin/assets/1311555/ab214d66-502e-4fb4-ba6e-e4fac4c1d257)

Sorry I don't know what I'm supposed to change here to get this "thing" :(

**Comment by NoTitleGamesOfficial** [comment]
I'm using Classic4Lite. 

Your last image is the result I would like to have. Do you have some instructions how to get that, I never edited something with Shaders before.

**Comment by Zylann** [comment]
In the inspector, create a New Shader in the Custom Shader property:
![image](https://github.com/Zylann/godot_heightmap_plugin/assets/1311555/124274da-cde5-46a9-969f-bde3e44df622)
This will create a copy of the builtin shader you had selected before.

Then switch Shader Type to Custom so it will start using the custom copy.

Then click on the Shader property value:
![image](https://github.com/Zylann/godot_heightmap_plugin/assets/1311555/2e4b4bee-9128-4423-924d-ec0f18c077ca)

This will open the shader editor, in which you can add the line at the bottom:
![image](https://github.com/Zylann/godot_heightmap_plugin/assets/1311555/64dbadf7-3faa-4562-a2b8-f41cec32a6de)

**Comment by NoTitleGamesOfficial** [comment]
I get this error when I add a custom copy:

![Bildschirmfoto von 2023-10-15 21-58-46](https://github.com/Zylann/godot_heightmap_plugin/assets/105103092/8cf1e523-7310-464c-ac3e-4633aef6c314)

**Comment by Zylann** [comment]
That was fixed in the master branch of the plugin. Just write the full path:
```
#include "res://addons/zylann.hterrain/shaders/include/heightmap.gdshaderinc"
```

**Comment by NoTitleGamesOfficial** [comment]
So i got rid of the error, but nothing happens when adding the line? Do I need to somehow reload the terrain?

**Comment by Zylann** [comment]
No, it should just update immediately. Did you select `CUSTOM` in `shader type`?

**Comment by Zylann** [comment]
I exposed specular in built-in shaders in afb412d37c98754fb0eae3093465072487388ab1

**Comment by NoTitleGamesOfficial** [comment]
> No, it should just update immediately. Did you set `Shader Type` to `CUSTOM` in the inspector?

... that did the trick :D 
Thank you so much for your help and the great plugin. I'm currently poor but I'll spent you a coffee in the future ;)

**Comment by NoTitleGamesOfficial** [comment]
I'm currently trying to do this for Godot 3 version, too. 
But when I add 'SPECULAR = 0.0' to the classic4Lite shader, I get the issue " Unknown identifier in expression: SPECULAR"
Any ideas what I needed to do in the old version to get this done?
