### ISSUE TITLE
Color Paint erase

### ISSUE THREAD

**Issue by xxwassyxx** [Zylann/godot_heightmap_plugin#405]
I have tried searching high and low and feel like I am missing something very obvious. How do you remove something colored by the "color paint" tool? Is there an eraser option?

**Comment by Zylann** [comment]
Color it white?

**Comment by xxwassyxx** [comment]
So I actually tried that but I wasn't sure if its putting a white color behind it or erasing the color? Is a mesh white by default?

**Comment by Zylann** [comment]
It paints over whatever color was there before. Yes by default it is white.

**Comment by xxwassyxx** [comment]
Thank you, I realize a really dumb question I have been trying to understand now for some time. Thanks all
