### ISSUE TITLE
filter_nearest

### ISSUE THREAD

**Issue by AndrewBonk** [Zylann/godot_heightmap_plugin#406]
Is there a way to have the textures display with filter_nearest in the  classic4lite?

**Comment by Zylann** [comment]
It's not something that can be toggled, you have to modify the shader (Godot shader requirements, I really can't expose this as a checkbox in shader settings). 

Change these lines:
https://github.com/Zylann/godot_heightmap_plugin/blob/51ff429dffdf04004b9df296d444b2a512c481eb/addons/zylann.hterrain/shaders/simple4_lite.gdshader#L17-L20

Into this:
```glsl
uniform sampler2D u_ground_albedo_bump_0 : source_color, filter_nearest_mipmaps;
uniform sampler2D u_ground_albedo_bump_1 : source_color, filter_nearest_mipmaps;
uniform sampler2D u_ground_albedo_bump_2 : source_color, filter_nearest_mipmaps;
uniform sampler2D u_ground_albedo_bump_3 : source_color, filter_nearest_mipmaps;
```

Or fork the shader and do the changes. Forking can be done by creating a new shader in the Custom Shader property (this will create a copy of the current built-in shader; you can also copy the code manually), and set the Shader Type to Custom.

**Comment by AndrewBonk** [comment]
Hi when I apply these changes I get an error saying:"Expected valid type hint after ":"".

**Comment by AndrewBonk** [comment]
> It's not something that can be toggled, you have to modify the shader (Godot shader requirements, I really can't expose this as a checkbox in shader settings).
> 
> Change these lines:
> 
> https://github.com/Zylann/godot_heightmap_plugin/blob/51ff429dffdf04004b9df296d444b2a512c481eb/addons/zylann.hterrain/shaders/simple4_lite.gdshader#L17-L20
> 
> Into this:
> 
> ```glsl
> uniform sampler2D u_ground_albedo_bump_0 : source_color, filter_nearest_mipmaps;
> uniform sampler2D u_ground_albedo_bump_1 : source_color, filter_nearest_mipmaps;
> uniform sampler2D u_ground_albedo_bump_2 : source_color, filter_nearest_mipmaps;
> uniform sampler2D u_ground_albedo_bump_3 : source_color, filter_nearest_mipmaps;
> ```
> 
> Or fork the shader and do the changes. Forking can be done by creating a new shader in the Custom Shader property (this will create a copy of the current built-in shader; you can also copy the code manually), and set the Shader Type to Custom.

**Comment by NascentSpace** [comment]
Thank you so much! I've been stuck trying to figure this out for an hour ;-;
