### ISSUE TITLE
Lowering of terrain not showing up for single coordinates

### ISSUE THREAD

**Issue by faweizz** [Zylann/godot_heightmap_plugin#411]
Hi! Im working on a project where the terrain can be deformed at runtime. So far, this is working fine. But when single coordinates are lowered under the level of the surrounding coordinates, it shows some weird behaviour:

1. Detail is sinking correctly with the coordinate
2. The collision layer is sinking correctly with the coordinate
3. But the mesh seems like its forming some kind of convex hull around the points
4. When i drop the camera into this hole, it seems like the mesh is forming correctly underneath, but due to the hull, its not visible

When raising single coordinates, this works as expected and a spike is formed.

Im using the MULTISPLAT16 shader. There seems to be no change, when i apply other shaders.

Can i turn this behaviour off? (or is this a bug on my side?)

**Comment by Zylann** [comment]
By single coordinates, you mean raising/lowering a single pixel of the heightmap? This is definitely bound to accuracy issues, I wouldn't rely on this because it looks really bad either way, as there is not enough triangles.
I'm also confused as to how lowering has any different effect than raising, there is no different code to handle either, it works the same.

> Can i turn this behaviour off? (or is this a bug on my side?)

You can't turn off "not enough resolution", it's an inherent problem of modifying single pixels 🤔 but I might misunderstand what you mean tbh. I have no idea what is that convex hull you are referring to. Do you have screenshots? An MRP?

**Comment by faweizz** [comment]
Thanks for your response. I looked further into the issue and noticed that this behaviour also only affects certain x/z regions of my map. 

![image](https://github.com/Zylann/godot_heightmap_plugin/assets/19994524/080f088c-18c5-42ac-9e28-f273cb3e9d1b)

The resulting effects is visible in the screenshot above: The terrain clips through the details, whereas you can see "correct" details on the topright. The area where the details are clipping is lower than the terrain on the top right.

When i lower the terrain in the area where the details are clipping further, the details/collision will lower as expected. The terrain stays the same.

**Comment by Zylann** [comment]
Can you make a minimal reproduction project? Because I fail to understand what I'm really looking at or what would be the cause of this.

**Comment by faweizz** [comment]
The repro is not finished, but I managed to find out more. I will propably provide it this weekend. 

What I managed to find out is the following: When I create a gdscript with 2 functions which are called externally, one being init and one being an update, I can reproduce the issue. 

The init function just initialises a terrain/data and adds it as a child. 

The update call writes height data to the terrain and updates it. 

When I call init/update with some time in between, the issue appears. When I write the data directly after instantiating the terrain, the terrain behaves as expected. 

What I’m currently not doing is updating the terrain normals as you are referring to in the documentation about programmatically updating the terrain. Could this lead to a problem as such?

**Comment by Zylann** [comment]
> What I’m currently not doing is updating the terrain normals

That should not affect the heightmap.

**Comment by faweizz** [comment]
Sorry for the delay but i managed to finish the repro: https://github.com/faweizz/hterrainrepro

The issue while reproducing was, that the behavior only shows when the camera is near the updated terrain. When i move the camera away and return, the mesh shows correctly.

The repro loads a piece of my heightmap after the hterrain has been instantiated, the camera is placed near the spot where you can see the issue.

**Comment by Zylann** [comment]
Is C# required to run this project? I see a `repro.gd` but I can't open scene.tscn

**Comment by Zylann** [comment]
Looks like some chunks are overlapping for some reason.
One workaround you can use for now is to call `terrain._reset_ground_chunks()` after `notify_region_change`

**Comment by Zylann** [comment]
I think I found a fix in 0b7093270f5a9a77141b8df1d83d6f8b16c4a6db
It's very old code, let me know if it works for you

**Comment by faweizz** [comment]
Yes, if that’s a problem I will rewrite it asap

**Comment by faweizz** [comment]
This fixes it :)
