### ISSUE TITLE
LOD Scale Slider does not update its own value

### ISSUE THREAD

**Issue by alexsincennes** [Zylann/godot_heightmap_plugin#412]
**Describe the bug**
In the properties of HTerrain, the "LOD Scale" slider does not update its own value, despite setting the split scale internally. The result is a LOD Scale slider stuck at a value of 2.

**To Reproduce**
1. Create a new scene
2. Add an HTerrain node
3. Go to its properties and try to move the LOD Scale slider. 
4. Observe that it is stuck at 2.

**Expected behavior**
It should behave as a normal slider, at its clamped values between 2 and 5.

**Environment**
- OS: Windows 11
- Graphics card: Nvidia RTX 4090
- Godot version: 4.1.3 (mono)
- Plugin version: 1.7.2
- Renderer used: forward_plus

**Proposed Solution**
Update the setter of the slider to update its own value 

https://github.com/Zylann/godot_heightmap_plugin/blob/master/addons/zylann.hterrain/hterrain.gd#L158-L159

```
@export_range(2, 5) var lod_scale := 2.0:
	get:
		return lod_scale
	set(value):
		if (lod_scale == value):
			return
		lod_scale = value
		_lodder.set_split_scale(value)
```

**Comment by Zylann** [comment]
Fixed in 1a6c5cc2e7567de5970c0466e90415352c022407
