### ISSUE TITLE
Assertion Failed

### ISSUE THREAD

**Issue by polkao** [Zylann/godot_heightmap_plugin#413]
**Describe the bug**

**To Reproduce**
Linking a reproduction project may help.
If you see any errors in the console, that may also help.

**Expected behavior**

**Screenshots**

**Environment**
- Graphics card (you can find out in Godot's console log)
- Godot version [e.g. 3.2.1]
- Plugin version (or commit hash if you got it from Github directly)
- Renderer used: note that GLES2 is not supported.

**Comment by polkao** [comment]
i cant use the brush it always error

**Comment by Zylann** [comment]
Please fill in the issue template. I can't do anything without any information about your issue.
