### ISSUE TITLE
Feature proposal: Add a way to scale texture

### ISSUE THREAD

**Issue by nanto2016** [Zylann/godot_heightmap_plugin#431]
I currently have an HTerrain and the I have a grass texture on it. I find the texture too big and I would like each texture tile to be smaller.

If there was a simple "texture scale" property (just like Node3D.scale, except it would be Vector2) that would scale the texture before applying it to the HTerrain surface, this would fix my problem.

I thought of scaling down the entire HTerrain but to me, that seems like a really bad idea and that would not work well if you already built a good terrain. I searched for a feature like the one I am suggesting here but found nothing that could help. The best temporary solution would be to tile the texture in its file so that the texture is larger and is displayed smaller on the HTerrain but this is not very data efficient (takes extra disk space), and I think that a way to scale the texture would be very easy to implement.

What the problem looks like, the grass is too big:
![image](https://github.com/Zylann/godot_heightmap_plugin/assets/118000184/5e0104fa-ba92-447c-949e-7c7db1f021c7)

Temporary solution, grass is smaller:
![image](https://github.com/Zylann/godot_heightmap_plugin/assets/118000184/c8f89849-a513-42ba-833e-b976211d8a36)

**Comment by Zylann** [comment]
I think every shader already has an option to scale textures, with the `u_ground_uv_scale` property. Check the Shader Params category in the inspector.
The Classic4 shader even has `u_ground_uv_scale_per_texture` which allows to scale each texture individually.
If that's not enough for you, you can easily modify/fork the shader and add the scaling parameters you want.
