### ISSUE TITLE
godot 4.3.dev5 error on active

### ISSUE THREAD

**Issue by yythlj** [Zylann/godot_heightmap_plugin#433]
thanks for reply.
I found another error when I active this plugin

Cannot connect to 'changed': the provided callable is not valid: ShaderMaterial::_shader_changed

And when I disactive the plugin the error disappear.
 at: (core/object/object.cpp:1385)

![image](https://github.com/Zylann/godot_heightmap_plugin/assets/33251075/c79cac01-e65d-4413-a17a-643eef8192a2)
![image](https://github.com/Zylann/godot_heightmap_plugin/assets/33251075/667eca8a-ddea-4540-859d-5811bc8dfce3)

what amazing : when I choose to the   Compatibility, the error disapear too.
![image](https://github.com/Zylann/godot_heightmap_plugin/assets/33251075/35ef9566-43e7-4b28-9e0f-77f358227a96)

**Comment by Zylann** [comment]
I'm not sure if that error is because of the plugin? If it only happens in Godot 4.3 dev5 (which is not even a stable version) or is specific to a particular renderer, it could be a Godot bug.

**Comment by yythlj** [comment]
yes.only active the plugin and on the forward+ woll occur



---Original---
From: ***@***.***&gt;
Date: Tue, Apr 16, 2024 01:34 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Zylann/godot_heightmap_plugin] godot 4.3.dev5 error on active(Issue #433)




 
I'm not sure if that error is because of the plugin? If it only happens in Godot 4.3 dev5 (which is not even a stable version) or is specific to a particular renderer, it could be a Godot bug.
