### ISSUE TITLE
godot4.3.dev5 headless profile not good

### ISSUE THREAD

**Issue by yythlj** [Zylann/godot_heightmap_plugin#434]
In my Godot project, I separated the server code and client code to implement a PVP room game. However, after testing, in scenes with similar objects, the FPS of the server differs greatly between using an hterrain map scene and using a regular glb object scene imported.

Both were tested under the headless display server mode (for the server, rendering is unnecessary, the purpose is to improve computational performance).

When there was only one room, the difference between the two was negligible, the server could reach 75FPS.
When the number of rooms reached 50 (4 people), the FPS of hterrain dropped to between 4-6, while the regular scene could maintain 9-12FPS.

Is there a way to disable unnecessary rendering calculations in headless mode?（not create any hterrain detail layer）
I only want it to effect collide on th server app side.visible is not important

![image](https://github.com/Zylann/godot_heightmap_plugin/assets/33251075/f9e56d47-a45e-4b38-8c11-5c4453f3d97b)

other:
![image](https://github.com/Zylann/godot_heightmap_plugin/assets/33251075/435657f8-6f47-4e70-ba31-a4cd6b676382)

**Comment by yythlj** [comment]
I just hide the window,and make no camera is current(I create each room as a window by use its own world3d,and the hterrain is the child of a node on the window)



---Original---
From: ***@***.***&gt;
Date: Wed, Apr 17, 2024 02:04 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Zylann/godot_heightmap_plugin] godot4.3.dev5 headless profilenot good (Issue #434)




 
Did you try hiding the node?

**Comment by Zylann** [comment]
Hiding the node and calling `terrain.set_process(false)` might help
