### ISSUE TITLE
HTerrainDetailedLayer issues using centered maps

### ISSUE THREAD

**Issue by antzGames** [Zylann/godot_heightmap_plugin#446]
**Describe the bug**

Tested on both Godot 4.2.2 stable and 4.3.b6

HTerrainDetailedLayer has issues with centered maps.

When using centered maps, HTerrainDetailedLayer does not show up on the editor (until you toggle centered maps).  Once that is done, then they show up in the editor.

However when you build and run the application then HTerrainDetailedLayer does not show up on centered maps

If I turn OFF centered maps (prior to running) and when you move to the areas with detail the grass shows up.

But its all around buggy when using centered maps as the video shows below:

https://github.com/Zylann/godot_heightmap_plugin/assets/10563814/ab1fb543-d251-4e78-9a55-12cb56f97f8b

Based on the FPS drops, it seems the instanced trees are on the other side of the map.

**Environment**
- OS: Windows 11
- Graphics card: RTX 3050
- Godot version: 4.2.2 + 4.3.b6
- Plugin version (or commit hash if you got it from Github directly)
- Renderer used: Compatibility

**Comment by Zylann** [comment]
> When using centered maps, HTerrainDetailedLayer does not show up on the editor (until you toggle centered maps)

I dont understand. To use centered maps, you have to toggle centered maps. How is the issue about centered map showing before you even enable the option?

The video doesn't really help, while I see the issue there is too much going on, it's also not thought to be modified while in-game (might work, might not, the fact this is even possible is just Godot allowing that).

I'm not sure how to reproduce all that. I opened one of my test scenes, I enabled `centered`, then moved to the location I had grass on, and grass showed up as normal.
I moved my player next to that area and played the scene. Grass also showed up as normal.

> Plugin version (or commit hash if you got it from Github directly)

Which version are you using?

> Renderer used: Compatibility

I'm not sure if the plugin works on that renderer. But that might not be related to the issue.

**Comment by antzGames** [comment]
I am using 1.7.2.  Let me try 1.7.3

**Comment by antzGames** [comment]
Everything worked on the first try with 1.7.3 DEV.  Thx.  Closing issue.
