### ISSUE TITLE
Can't Texture Paint

### ISSUE THREAD

**Issue by Coolkid-dotcom** [Zylann/godot_heightmap_plugin#452]
Hi. Whenever I select a texture and attempt to paint it onto the terrain I get this error: res://addons/zylann.hterrain/tools/brush/terrain_painter.gd:304 - Assertion failed.

No Idea what to do, as I am new to this type of stuff and Godot in general

I have a RTX 3060, Windows 11 x64, and GLES 3 (I think, I don't know how to check). I also have godot 4.2.2.

Any help on this would be extremely appreciated.

Thanks!!!

**Comment by Zylann** [comment]
Is that still happening if you restart the editor? Are there other things in the logs before this one? I can texture paint just fine when using the latest version in the repo (and I don't think anyone reported such an error with the older version on the assetlib, and it's been there *a very long time*) so it's really unclear to me what's different in your very specific case.

**Comment by Coolkid-dotcom** [comment]
I downloaded the latest plugin version from the asset library built in to Godot. And no error messages are printed before I begin painting. In terms of the potential issues that you have listed, none of these were the case, and the error still appears after restarting the editor. Idk any other way to reproduce other than downloading the plugin from the assetlib, loading a texture, and attempting to paint it. Don't know anything else.

**Comment by Coolkid-dotcom** [comment]
NVM. Found the issue!!! Turns out I set the shader mode to Low Poly instead of Classic4Lite. So It works!!!

**Comment by Zylann** [comment]
> I downloaded the latest plugin version from the asset library built in to Godot

Did you try with the repo version instead? Just trying to rule out a potential issue that has been fixed since, because I still have no idea what could possibly cause this.

> Turns out I set the shader mode to Low Poly instead of Classic4Lite

Ah, that's probably a bug then, but it's also expected for painting to do nothing here because this shader doesn't support texture painting. So the issue is rather that the issue is not reported clearly in the UI.

**Comment by Coolkid-dotcom** [comment]
Ok. Anyways, thanks for the help.
