### ISSUE TITLE
Regen multimesh

### ISSUE THREAD

**Issue by yythlj** [Zylann/godot_heightmap_plugin#459]
I found the most fps eat by this function call
if I change this line add a randi ratio as 5%
the fps can be high

	if _multimesh_need_regen and randi() % 100 < 5:
		print("Regen multimesh")
		_regen_multimesh()
		_multimesh_need_regen = false
		# Crash workaround for Godot 3.1
		# See https://github.com/godotengine/godot/issues/32500
		for k in _chunks:
			var chunk : Chunk = _chunks[k]
			chunk.mmi.set_multimesh(_multimesh)

**Comment by Zylann** [comment]
> I found the most fps eat by this function call

That makes no sense considering that line is only supposed to run once after you change density, and never again.
Have you found that it runs every frame for some weird reason? Because it should not. That `rand()` should not be necessary,
