### ISSUE TITLE
How can I make a larger map?

### ISSUE THREAD

**Issue by SlimyFrog123** [Zylann/godot_heightmap_plugin#463]
(Godot 3 version)

I am making a game, but I need a very large world for the style of game it is. Is there any way for me to create one bigger than it allows by default? (Maybe something I can change in the script to allow for larger predetermined sizes?) Or is there any official way to combine multiple into one?

If I need to, I will just make multiple and put them together, matching height at the borders, but I'd really like to have it just be one, since it's tedious to transfer every edit I make onto the server, and having to do that more than once per time I change the map is annoying.

(Just want to thank you for all the work you've done on the plug-in; it's a lifesaver!)

Thanks in advance!

**Comment by Zylann** [comment]
That plugin is not suitable as-is for extremely large single terrains. The easiest you can do is increase the resolution or change the limit in scripts, combined with some scaling, but anything too large requires more fundamental changes that I'm not planning (or have time) to do.
