### ISSUE TITLE
No Splatmap generated?

### ISSUE THREAD

**Issue by Lunrae** [Zylann/godot_heightmap_plugin#471]
I was going to try and use the splatmap to do a footsteps system, but while the color, normal and heightmap of the terrain were generated correctly, the splatmap is just an empty file.

I don't know if it's a bug, or if there's something I'm missing. I guess I could make a color map to circumvent that problem but that's not exactly ideal.
![image_2024-12-07_164204354](https://github.com/user-attachments/assets/cce7a63d-b393-4822-b395-038d9e6e86c2)
![image](https://github.com/user-attachments/assets/6538b618-34d7-497a-aa26-f82f12ec079a)

Thank you!

**Comment by Zylann** [comment]
Splatmaps use all 4 channels, including the alpha channel. By default, only the red channel is 1, all others are 0. Which means alpha is 0, and so if you look at the image, it will look totally transparent. But there is data in there.
If you want to inspect the splatmap without this caveat of image viewers, you can use the lookdev mode in the Terrain menu, or you can use an image editor that lets you visualize each channel independently, or open the image with RenderDoc which also has an option to inspect channels.

**Comment by Lunrae** [comment]
Ooh so it was me who didn't understand indeed. I found it weird that the image clearly had a filesize which meant it had data. Noobie dev here.

Thanks a lot for the quick answer and for the plugin! It's helping me a lot.
