### ISSUE TITLE
Bad download hash when installing

### ISSUE THREAD

**Issue by katznboyz1** [Zylann/godot_heightmap_plugin#59]
![bdherror](https://user-images.githubusercontent.com/38505228/50060250-a7c90200-015f-11e9-8b97-10524a5fc05d.png)

**Comment by Zylann** [comment]
Did you try to retry downloading the asset?

**Comment by katznboyz1** [comment]
I tried several times over the course of a few minutes

**Comment by Zylann** [comment]
I'm getting it as well... this is very strange.
Meanwhile you could try getting it manually from https://codeload.github.com/Zylann/godot_heightmap_plugin/zip/8df7efbbcd97e8b93446035a851e04f98beb963c

**Comment by katznboyz1** [comment]
Thanks!
