### ISSUE TITLE
terrain_generator.shader is missing

### ISSUE THREAD

**Issue by csaga77** [Zylann/godot_heightmap_plugin#63]
Just checked out the plugin and found res://addons/zylann.hterrain/tools/generator/shaders/terrain_generator.shader is missing.
<img width="811" alt="screen shot 2018-12-31 at 8 13 28 pm" src="https://user-images.githubusercontent.com/12321801/50558294-94f62600-0d38-11e9-92b1-148e3bb2f221.png">

**Comment by Zylann** [comment]
It is unused, I removed that line but I probably didn't push it yet.

**Comment by Zylann** [comment]
Should be fixed by 1f816c8338176bec02088ce07879f5ec2d4ee22c once merged

**Comment by Zylann** [comment]
The `saving` branch was merged to `master`.
