### ISSUE TITLE
Godot 3.1 alpha4 cannot load grayscale EXR files

### ISSUE THREAD

**Issue by Zylann** [Zylann/godot_heightmap_plugin#64]
This is a reminder for myself to undo this workaround, which prevents the crash but disables custom brushes: c25fc9ba6f11672abbf04434ff3a7bf9ce155d88
The plugin needs to load a greyscale .exr image but Godot 3.1 alpha4 crashes or fails to load it.
Depends on https://github.com/godotengine/godot/issues/24641

**Comment by capnm** [comment]
> The plugin needs to load a greyscale .exr image

FYI I have a similar issue. Even though https://github.com/syoyo/tinyexr/issues/99 is fixed, Godot itself does not support the gray channel (no more a crash but an error). As before only 'gray' RGBs are recognized ;)

**Comment by Zylann** [comment]
😭 
Can you open a new issue then?
This will need to be reopened then https://github.com/godotengine/godot/issues/24247

**Comment by Zylann** [comment]
I believe this is fixed now.
