### ISSUE TITLE
Godot 3.1 x64 segfaults while loading the plugin

### ISSUE THREAD

**Issue by alxgb** [Zylann/godot_heightmap_plugin#67]
I'm using the Windows x64 build provided by the team. Betas 1, 2 and 3 crash.

It crashes while importing acrylic1.exr, or at least that's the last thing I see before the editor segfaults. No errors that I could spot on the log output. Interestingly, it does work on the 32 bit editor and once it's imported there both the x64 and x32 versions load fine (and HTerrain is available, etc). I guess this is an upstream (engine) issue, but I don't know if it could be worked around.

I don't know if this is related to #64 in any way, as I understand that one is specifically about *some* .exr unsupported images, not all?

**Repro:** 
a) I just used a new blank project to add the plugin to, and copied the latest master into it. Doesn't matter if the editor is open or closed when added, it'll crash as soon as it imports.

b) This very repo can also serve to reproduce the issue, the moment I try to open it with win64 Godot it crashes.

**Comment by Zylann** [comment]
This is not caused by the plugin, this is again the same cause from #64, Godot crashes when it tries to import this EXR. I temporarily disabled loading of EXRs from the plugin, but Godot is still trying to import them.
See https://github.com/godotengine/godot/issues/24641

**Comment by alxgb** [comment]
Solved in the engine!
