### ISSUE TITLE
smoother holes

### ISSUE THREAD

**Issue by pgruenbacher** [Zylann/godot_heightmap_plugin#73]
Hi Zylann, 

You got any idea on how to increase the resolution on the color map texture (for hole masks)? 

![screenshot from 2019-03-02 17-51-17](https://user-images.githubusercontent.com/3332598/53688566-df355c80-3d13-11e9-831e-c7c1b5527a54.png)

Actually in the process I ended up thinking of a solution... your simple4.shader is getting the tint texture in the vertex shader instead of fragment (for perf. reasons, but that explains why the holes match the vertices LOD...). But I think LOD holes are non-ideal since they can become quite obvious at far distances...

I'll keep the issue to document my progress..

**Comment by pgruenbacher** [comment]
![screenshot from 2019-03-02 18-02-03](https://user-images.githubusercontent.com/3332598/53688666-528b9e00-3d15-11e9-929c-b34239485758.png)

ah ok so moving the  code to the fragment does the trick...
````
void fragment() {
	vec4 v_tint = texture(u_terrain_colormap, UV);
	if(v_tint.a < 0.5) {
			// TODO Add option to use vertex discarding instead, using NaNs
			discard;
	}
```

**Comment by pgruenbacher** [comment]
https://github.com/godotengine/godot/issues/10241
looks like antialising doesn't work on godot 3.1 or 3.0 from what I can tell... guess will have to wait then...

**Comment by Zylann** [comment]
Note that in practice, I don't intent to make holes "beautiful". They exist because it allows to then place a mesh on top of the edges, which are not supposed to be seen in the end. For example, a cave entrance or a tunnel should have rocks or bricks all around the hole.

**Comment by pgruenbacher** [comment]
Ah that's because I didn't show the picture of the trench I made. It's less
to do with beautiful and more to do with high aspect holes which is due to
my game involving wwi
