### ISSUE TITLE
Grass not placed correctly when height of terrain is scaled

### ISSUE THREAD

**Issue by ThunderFD** [Zylann/godot_heightmap_plugin#83]
if you scale the terrain on the y axis, which I did (I did 0.5 on x,y,z before I started) grass will not be planted on the surface, since the grass position doesn't seem to be scaled vertically!

edit: with height I mean the "map scale" field

**Comment by ThunderFD** [comment]
here's a screenshot:
![image](https://user-images.githubusercontent.com/17814079/58660558-01944180-8326-11e9-9ea1-5f906ca09f71.png)

**Comment by ThunderFD** [comment]
oops, same issue as #74

**Comment by Zylann** [comment]
Duplicate of #74 indeed, I noticed it during a game jam too. Will have a look in a moment.

**Comment by ThunderFD** [comment]
cool! I fixed it in #84 - you could just merge that
