### ISSUE TITLE
The lights doesn't affect the terrain on MacOs

### ISSUE THREAD

**Issue by ardawan** [Zylann/godot_heightmap_plugin#85]
I've tried to install from Godot asset from the editor "Heightmap Terrain" by Zylann ( but when I activate the plugin I see the author name is "Marc Gilleron" ! ). I managed to activate the plugin and add the HTerrain node to my scene.

After setting the data folder to the HTerrain I got the black terrain and fortunately, I'm able to make some hight via the brushes.

After that, I've added directionalLight node to make some lights on the terrain. But the terrain still is black even though I've saved the project and reopen the Godot.

**My specs:
MacOs 10.14
Godot 3.1**

Is that a bug?

<img width="1437" alt="Screen Shot 2019-06-05 at 9 15 38 AM" src="https://user-images.githubusercontent.com/6112301/58923499-90fc8300-8772-11e9-9dae-9b4f8dea6177.png">

**Comment by ardawan** [comment]
I changed the shader type to classic4lite and it worked.

**Comment by Luthien-in-edhil** [comment]
I have the same issue. Changing the shader to classic4lite is maybe a temporary workaround but it's still a bug ... would you maybe consider reopening the issue?

**Comment by ardawan** [comment]
I'm not sure the problem is about the plugin or the Godot itself, that's why I never reported. 
I've never encountered the same issue on a Linux machine. so I guess the bug is in Godot Engine.
