### ISSUE TITLE
No se crea el terreno en GLES, 2.0, necesita soporte !!!

### ISSUE THREAD

**Issue by esbvaGames** [Zylann/godot_heightmap_plugin#87]
No se puede crear el Terreno en la versión 3.1, cuando se usa con el controlador de GLES 2.0, necesita un soporte de edición, y que contenga los shaders de menor calidad, si no se puede hacer shaders al menos la malla con una textura simple, tampoco se ven las brochas, y de cuando en cuando se cuelga XD  !!!

**Comment by Zylann** [comment]
Going to close this one as it's a duplicate of #96
