### ISSUE TITLE
Syntax error with Godot 3.2 (indentation)

### ISSUE THREAD

**Issue by MilosLukic** [Zylann/godot_heightmap_plugin#93]
Hello, I tried the plugin with Godot 3.2 and there is a syntax error, I looked a bit deeper and found that Plugin.gd file, last character of the file is a space and which triggers the "space indent in tab indented file". Looks like new godot will have strict tab/space identation policy, so removing that space would make it work out of the box.

**Comment by Zylann** [comment]
Fixed in 48f1510cdf927a6e020bc41d2ebd6a066c750ab3
