### ISSUE TITLE
Apply objects movement effects on terrain

### ISSUE THREAD

**Issue by siamak-s** [Zylann/godot_heightmap_plugin#95]
How we can apply objects movement effect (like car wheels, object fall position and etc) on the terrain? 
Something like runtime texturing with one of four ground textures or runtime terrain coloring.
For example, at the end of this video shows a nice car wheel movement effect on the ground:
[https://www.youtube.com/watch?v=eR_RHP4G-kQ](url)

**Comment by Zylann** [comment]
This video shows simulation of one wheel, in Blender, by modifying geometry of a single flat plane. This approach may look good for a movie, but in realtime with a game engine, this doesn't scale at all.

This probably needs decals or flat trails instead, which isn't really a feature related to terrains.
